# -*- coding: utf-8 -*-
# File: models/stock_rule.py
# Module: clinic_inventory
#
# Purpose
#   Extend stock.rule for aesthetic clinics:
#   - Rule-level clinic policies (FEFO enforcement hint, minimum shelf-life, replenishment scope)
#   - Destination resolution helpers that honor clinic warehouse configuration (pharmacy / treatment rooms)
#   - Safer stock move value enrichment for traceability (no new move fields—use name/notes and rule linkage)
#   - Hook methods for 25 ClinicOne addons to inject procurement/routing logic without circular deps
#
# Notes
#   - All user-facing strings are in English.
#   - We do not change valuation or accounting; only routing/procurement hints.
#   - We avoid passing unknown keys to stock.move values to remain compatible with Odoo core.

from datetime import date, timedelta

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError, UserError


class StockRule(models.Model):
    _inherit = "stock.rule"

    # =========================================================================
    # Clinic-level policy controls (per rule)
    # =========================================================================
    clinic_enforce_fefo = fields.Boolean(
        string="Enforce FEFO (Clinic)",
        tracking=True,
        help=(
            "Hint to enforce FEFO (First-Expire-First-Out) for moves created by this rule.\n"
            "Odoo's FEFO is primarily driven by Location Removal Strategy. This flag is "
            "an additional policy indicator read by clinic bridges/reservation hooks."
        ),
        default=True,
    )

    clinic_min_shelf_life_days = fields.Integer(
        string="Min Remaining Shelf Life (Days)",
        tracking=True,
        help=(
            "If set, procurement/reservation SHOULD avoid lots that would expire in fewer "
            "than this number of days when fulfilling moves generated by this rule.\n"
            "Bridges may enforce this at reservation time."
        ),
        default=0,
    )

    clinic_replenishment_scope = fields.Selection(
        selection=[
            ("pharmacy_only", "Pharmacy Only"),
            ("rooms_only", "Treatment Rooms Only"),
            ("pharmacy_and_rooms", "Pharmacy and Treatment Rooms"),
            ("warehouse_default", "Warehouse Default"),
        ],
        string="Clinic Replenishment Scope",
        tracking=True,
        default="warehouse_default",
        help=(
            "Scope of internal replenishment for moves created by this rule. "
            "If 'Warehouse Default', the Warehouse setting is used."
        ),
    )

    clinic_destination_policy = fields.Selection(
        selection=[
            ("rule_dest", "Use Rule Destination"),
            ("pharmacy", "Send to Pharmacy"),
            ("treatment_root", "Send to Treatment Rooms Root"),
        ],
        string="Clinic Destination Policy",
        default="rule_dest",
        tracking=True,
        help=(
            "Override destination resolution for PUSH/internal rules:\n"
            "- Use Rule Destination: respect 'location_dest_id' on the rule.\n"
            "- Send to Pharmacy: route into the warehouse pharmacy location.\n"
            "- Send to Treatment Rooms Root: route under the treatment rooms root."
        ),
    )

    clinic_allow_expired_in_exception = fields.Boolean(
        string="Allow Expired in Exception",
        tracking=True,
        help=(
            "If enabled, bridges may allow expired lots to be used as an exception after explicit approval. "
            "Base module still follows warehouse/location policies; this flag is advisory."
        ),
        default=False,
    )

    # Traceability helpers / counters
    clinic_generated_move_count = fields.Integer(
        string="# Moves (Recent)",
        compute="_compute_clinic_generated_move_count",
        help="Approximate number of stock moves created recently by this rule (best-effort).",
    )

    # =========================================================================
    # COMPUTES
    # =========================================================================
    def _domain_recent_moves(self):
        # last 30 days
        today = fields.Date.context_today(self)
        return [
            ("rule_id", "in", self.ids),
            ("date", ">=", today - timedelta(days=30)),
        ]

    def _compute_clinic_generated_move_count(self):
        Move = self.env["stock.move"]
        for r in self:
            r.clinic_generated_move_count = Move.search_count(r._domain_recent_moves()) if r.ids else 0

    # =========================================================================
    # CONSTRAINTS
    # =========================================================================
    @api.constrains("clinic_min_shelf_life_days")
    def _check_min_shelf_life(self):
        for r in self:
            if r.clinic_min_shelf_life_days and r.clinic_min_shelf_life_days < 0:
                raise ValidationError(_("Min Remaining Shelf Life (Days) cannot be negative."))

    @api.constrains("clinic_destination_policy", "location_dest_id", "action")
    def _check_destination_policy(self):
        for r in self:
            if r.action not in ("push", "pull_push"):
                # Destination only meaningful for push/pull_push
                continue
            if r.clinic_destination_policy == "rule_dest" and not r.location_dest_id:
                raise ValidationError(_("Destination Policy is 'Use Rule Destination' but no Destination Location is set."))

    # =========================================================================
    # MOVE VALUE ENRICHMENT (safe—no new move fields)
    # =========================================================================
    def _get_stock_move_values(
        self, product_id, product_qty, product_uom, location_id, name, origin, company_id, values
    ):
        """Enrich stock move values with clinic-aware hints while keeping them core-safe.

        We do NOT add unknown keys to the move; instead we:
          - Adjust 'name' and 'description_picking' to include clinic hints.
          - Potentially update 'location_dest_id' based on clinic destination policy.
          - Optionally set 'date_deadline' to now + min_shelf_life (soft hint for planning).
        """
        move_vals = super()._get_stock_move_values(
            product_id, product_qty, product_uom, location_id, name, origin, company_id, values
        )
        # Resolve product/warehouse
        product = self.env["product.product"].browse(product_id)
        warehouse = self.warehouse_id or getattr(self.picking_type_id, "warehouse_id", False)

        # 1) Resolve destination per clinic policy (push/internal flows)
        if self.action in ("push", "pull_push") and move_vals.get("location_dest_id"):
            dest = self._clinic_resolve_destination_location(move_vals.get("location_dest_id"), warehouse)
            if dest:
                move_vals["location_dest_id"] = dest.id

        # 2) Adjust move naming to carry clinic policy hints (visible in UI)
        tags = []
        if self.clinic_enforce_fefo:
            tags.append("FEFO")
        if self.clinic_min_shelf_life_days:
            tags.append("minSL=%sd" % self.clinic_min_shelf_life_days)
        if self.clinic_replenishment_scope and self.clinic_replenishment_scope != "warehouse_default":
            tags.append("scope=%s" % self.clinic_replenishment_scope.replace("_", "-"))
        if self.clinic_allow_expired_in_exception:
            tags.append("exp-exc")

        if tags:
            hint = " | ".join(tags)
            base_name = move_vals.get("name") or name or product.display_name
            move_vals["name"] = f"{base_name} [{hint}]"
            dp = move_vals.get("description_picking") or ""
            move_vals["description_picking"] = (dp + ("\n" if dp else "") + _("Clinic policy: %s") % hint).strip()

        # 3) Optional soft planning hint via date_deadline (NOT a strict rule)
        #    If min shelf life is set and product has expiration, we put a deadline today + threshold.
        if self.clinic_min_shelf_life_days and getattr(product.product_tmpl_id, "has_expiration", False):
            move_vals.setdefault("date_deadline", fields.Datetime.now() + timedelta(days=self.clinic_min_shelf_life_days))

        # 4) Allow bridges to adjust move values safely
        move_vals = self._clinic_hook_adjust_move_values(
            move_vals=move_vals,
            product=product,
            product_qty=product_qty,
            product_uom=self.env["uom.uom"].browse(product_uom),
            location_id=self.env["stock.location"].browse(location_id),
            origin=origin,
            warehouse=warehouse,
            raw_values=values or {},
        )
        return move_vals

    # =========================================================================
    # DESTINATION RESOLUTION
    # =========================================================================
    def _clinic_resolve_destination_location(self, current_dest, warehouse):
        """Resolve destination location according to clinic policy & warehouse configuration.

        Args:
            current_dest (stock.location | int): destination computed by core.
            warehouse (stock.warehouse|None): rule or picking type warehouse

        Returns:
            stock.location (could be the same as input)
        """
        Location = self.env["stock.location"]
        # ``self.env["stock.location"]`` is a recordset/proxy, not a type.
        # Core callers may provide either a stock.location recordset or an ID.
        dest = (
            current_dest
            if getattr(current_dest, "_name", None) == "stock.location"
            else Location.browse(current_dest)
        )
        policy = self.clinic_destination_policy or "rule_dest"
        if policy == "rule_dest":
            return dest

        wh = warehouse
        # Try to infer warehouse if not given, from dest
        if not wh and dest:
            wh = self.env["stock.warehouse"].search([("view_location_id", "parent_of", dest.id)], limit=1)

        if not wh:
            return dest  # cannot improve without a warehouse context

        if policy == "pharmacy":
            if getattr(wh, "clinic_pharmacy_location_id", False):
                return wh.clinic_pharmacy_location_id
            return dest  # fallback

        if policy == "treatment_root":
            if getattr(wh, "clinic_treatment_root_location_id", False):
                return wh.clinic_treatment_root_location_id
            return dest

        return dest

    # =========================================================================
    # REPLENISHMENT SCOPE HELPERS (domains)
    # =========================================================================
    def clinic_location_domain_for_scope(self, warehouse):
        """Return a domain for quants restricted by clinic replenishment scope.

        If the rule scope is 'warehouse_default', fall back to warehouse setting.
        """
        self.ensure_one()
        scope = self.clinic_replenishment_scope or "warehouse_default"
        if scope == "warehouse_default":
            # Ask warehouse helper (see stock_warehouse.py)
            if hasattr(warehouse, "_clinic_hook_location_domain_for_replenishment"):
                return warehouse._clinic_hook_location_domain_for_replenishment()
            # fallback: all internal
            return [("location_id.usage", "=", "internal")]

        if scope == "pharmacy_only" and getattr(warehouse, "clinic_pharmacy_location_id", False):
            return [("location_id", "child_of", warehouse.clinic_pharmacy_location_id.id)]
        if scope == "rooms_only" and getattr(warehouse, "clinic_treatment_root_location_id", False):
            return [("location_id", "child_of", warehouse.clinic_treatment_root_location_id.id)]
        # pharmacy_and_rooms → internal under warehouse view
        return [("location_id", "child_of", warehouse.view_location_id.id)]

    # =========================================================================
    # UI ACTIONS
    # =========================================================================
    def action_view_recent_moves(self):
        """Open stock moves created recently by this rule."""
        self.ensure_one()
        action = self.env.ref("stock.stock_move_action").read()[0]
        action["domain"] = self._domain_recent_moves()
        action["context"] = {"search_default_group_by_product": 1}
        return action

    # =========================================================================
    # HOOKS (override in bridge addons)
    # =========================================================================
    def _clinic_hook_adjust_move_values(
        self, move_vals, product, product_qty, product_uom, location_id, origin, warehouse, raw_values
    ):
        """Final adjustment hook for move values created from this rule.

        Bridges may:
          - attach clinical references (treatment/patient/doctor) by adding analytic tags on the move,
          - change 'date_deadline' according to appointment schedules,
          - tweak source/destination locations for specific departments,
          - apply coupon/membership annotations to 'description_picking'.

        IMPORTANT:
          - Do NOT add unknown keys to stock.move; keep changes to existing keys.
          - If extra state is needed, store it in models linked via rule_id, or override reservation logic.
        """
        return move_vals

    # =========================================================================
    # PUBLIC APIS (consumed by other modules)
    # =========================================================================
    def clinic_should_use_fefo(self):
        """Return True if this rule requests FEFO handling."""
        self.ensure_one()
        return bool(self.clinic_enforce_fefo)

    def clinic_min_shelf_life_threshold(self):
        """Return integer days of minimum remaining shelf life requested by this rule."""
        self.ensure_one()
        return int(self.clinic_min_shelf_life_days or 0)

    # =========================================================================
    # DEBUG / SUPPORT UTILITIES
    # =========================================================================
    def clinic_debug_preview_move_values(self, product, qty=1.0, src_location=None, origin=None):
        """Helper to preview move values generated by this rule (developer utility).

        Returns:
            dict (subset of move values)
        """
        self.ensure_one()
        if not src_location:
            src_location = self.location_src_id or (self.location_id if self.action in ("push", "pull_push") else False)
        if not src_location:
            raise UserError(_("No source location could be determined for preview."))

        move_vals = self._get_stock_move_values(
            product_id=product.id,
            product_qty=qty,
            product_uom=product.uom_id.id,
            location_id=src_location.id,
            name=_("Preview for %s") % product.display_name,
            origin=origin or "debug/preview",
            company_id=self.company_id.id,
            values={},
        )
        # Return a readable subset for debug
        keys = ["name", "product_id", "product_uom", "product_uom_qty", "location_id", "location_dest_id",
                "description_picking", "date_deadline"]
        return {k: move_vals.get(k) for k in keys}

