# -*- coding: utf-8 -*-
{
    "name": "ClinicOne - Audit & Compliance",
    "summary": "Immutable audit evidence, compliance governance, integrity verification, reviews, and evidence export.",
    "version": "19.0.2.0.3",
    "category": "ClinicOne/Compliance",
    "author": "IG @odoocamp",
    "website": "https://www.247opensource.com",
    "license": "AGPL-3",
    "depends": [
        "base",
        "base_setup",
        "mail",
        "web",
        "clinic_base",
        "clinic_branch",
    ],
    "data": [
        "security/clinic_audit_security.xml",
        "security/ir.model.access.csv",
        "data/clinic_audit_sequences.xml",
        "views/audit_event_views.xml",
        "views/audit_event_line_views.xml",
        "views/audit_policy_views.xml",
        "views/audit_review_views.xml",
        "views/audit_review_support_views.xml",
        "views/audit_verification_views.xml",
        "views/audit_legacy_views.xml",
        "views/res_config_settings_views.xml",
        "wizard/audit_evidence_export_views.xml",
        "wizard/audit_legacy_import_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
