{
    "name": "ClinicOne Enterprise Demo Dataset",
    "summary": "Deterministic, ownership-aware ClinicOne enterprise demo orchestration framework",
    "version": "19.0.1.0.46",
    "category": "ClinicOne/Configuration",
    "author": "ClinicOne",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "clinic_accounting", "clinic_analytics", "clinic_ap", "clinic_ar",
        "clinic_audit", "clinic_base", "clinic_billing", "clinic_booking",
        "clinic_branch", "clinic_care_plan", "clinic_consent_legal",
        "clinic_dashboard", "clinic_doctor", "clinic_ecommerce", "clinic_emar",
        "clinic_encounter", "clinic_feedback", "clinic_finance", "clinic_imaging",
        "clinic_incident_event", "clinic_insurance_authorization",
        "clinic_integration_api", "clinic_inventory", "clinic_l10n_id",
        "clinic_marketing", "clinic_membership", "clinic_package", "clinic_patient",
        "clinic_portal", "clinic_post_care_followup", "clinic_quality",
        "clinic_queue_room", "clinic_referral", "clinic_reports",
        "clinic_room_device", "clinic_staff", "clinic_telemedicine_secure_messaging",
        "clinic_treatment_catalog", "clinic_treatment_session",
        "clinic_triage_vitals", "clinic_wallet",
    ],
    "data": [
        "security/clinic_demo_security.xml", "security/ir.model.access.csv",
        "data/demo_sequence.xml", "views/demo_reference_views.xml",
        "views/demo_checkpoint_views.xml", "views/demo_log_views.xml",
        "views/demo_validation_views.xml", "views/demo_run_views.xml",
        "wizard/demo_reset_confirm_views.xml", "views/demo_menus.xml",
        "data/demo_menu_bridge.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
