
# -*- coding: utf-8 -*-
# File: clinic_doctor/models/schedule_rule.py
# Module: clinic_doctor
#
# ClinicOne — Schedule Rule (Odoo 19 CE ready)
#
# Purpose
# -------
# Weekly/recurring template that materializes concrete availability slots for doctors.
# The rule can target a doctor (required) and optionally a room & specialty. It supports:
# - Effective dates (date_start/date_end), week interval (e.g., every 2 weeks)
# - Float time in 24h format (start/end), slot duration, buffers
# - Capacity overrides per slot
# - Holiday/leave skipping (doctor leaves and resource calendar leaves)
# - Telemedicine-only rules
# - Holistic integration with other ClinicOne addons via guarded env checks
#
# Notes
# -----
# * All labels/help/messages use English (product requirement).
# * Timezone: rules are interpreted in a "local" timezone (rule_tz) and converted to UTC for storage.
#   Default tz is the doctor's user tz, else company tz, else 'UTC'.
# * This file assumes presence of `clinic.availability.slot` model for materialization.
#   If not installed, actions gracefully notify users.

from datetime import date, datetime, timedelta
from pytz import timezone, UTC

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError, UserError


WEEKDAY_SELECTION = [
    ("0", "Monday"),
    ("1", "Tuesday"),
    ("2", "Wednesday"),
    ("3", "Thursday"),
    ("4", "Friday"),
    ("5", "Saturday"),
    ("6", "Sunday"),
]


class ClinicScheduleRule(models.Model):
    _name = "clinic.schedule.rule"
    _description = "Doctor Schedule Rule"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _order = "sequence, doctor_id, weekday, start_time, id"

    # -------------------------------------------------------------------------
    # IDENTITY & SCOPE
    # -------------------------------------------------------------------------
    name = fields.Char(
        required=False,
        tracking=True,
        help="Friendly name for this rule. If left blank, a name is autogenerated."
    )
    sequence = fields.Integer(
        default=10,
        help="Display order."
    )
    active = fields.Boolean(
        default=True,
        help="Disable to stop generating availability from this rule."
    )
    company_id = fields.Many2one(
        "res.company",
        default=lambda self: self.env.company,
        required=True,
        index=True,
        help="Company for which this rule is applicable."
    )

    # -------------------------------------------------------------------------
    # TARGETS
    # -------------------------------------------------------------------------
    doctor_id = fields.Many2one(
        "clinic.doctor",
        required=True,
        ondelete="cascade",
        index=True,
        tracking=True,
        help="Doctor this rule belongs to."
    )
    room_id = fields.Many2one(
        "clinic.room",
        ondelete="set null",
        index=True,
        help="Optional room target for this rule."
    )
    specialty_id = fields.Many2one(
        "clinic.specialty",
        ondelete="set null",
        help="Optional specialty context/filter for this rule."
    )
    telemedicine_only = fields.Boolean(
        default=False,
        help="If enabled, the rule generates telemedicine (virtual) slots only."
    )

    # -------------------------------------------------------------------------
    # RECURRENCE (WEEKLY)
    # -------------------------------------------------------------------------
    weekday = fields.Selection(
        WEEKDAY_SELECTION,
        required=True,
        default="0",
        help="Weekday for this recurring rule."
    )
    interval_weeks = fields.Integer(
        default=1,
        help="Repeat every N weeks (1=every week, 2=every other week, etc.)."
    )
    date_start = fields.Date(
        help="First date when this rule takes effect. If empty, starts immediately."
    )
    date_end = fields.Date(
        help="Last date (inclusive) when this rule applies. If empty, no end date."
    )

    # -------------------------------------------------------------------------
    # TIME WINDOW (FLOAT TIME IN 24H)
    # -------------------------------------------------------------------------
    start_time = fields.Float(
        required=True,
        help="Start time in 24h float format (e.g., 9.0 = 09:00, 13.5 = 13:30)."
    )
    end_time = fields.Float(
        required=True,
        help="End time in 24h float format (must be greater than Start time)."
    )
    slot_duration_min = fields.Integer(
        default=30,
        help="Duration of each availability slot in minutes."
    )
    buffer_before_min = fields.Integer(
        default=0,
        help="Optional preparation buffer before each slot (minutes)."
    )
    buffer_after_min = fields.Integer(
        default=0,
        help="Optional cleanup buffer after each slot (minutes)."
    )
    capacity_per_slot = fields.Integer(
        default=0,
        help="Capacity override per slot. Set 0 to inherit from the doctor's default capacity."
    )

    # Computed next run datetime (for UX/cron visibility)
    next_occurrence_utc = fields.Datetime(
        compute="_compute_next_occurrence",
        store=False,
        help="Next date-time when this rule is expected to produce availability (UTC)."
    )

    # -------------------------------------------------------------------------
    # POLICIES
    # -------------------------------------------------------------------------
    skip_on_doctor_leave = fields.Boolean(
        default=True,
        help="Skip slot generation if the doctor has a leave overlapping the occurrence."
    )
    skip_on_calendar_leave = fields.Boolean(
        default=True,
        help="Skip slot generation if the doctor's calendar has a leave overlapping the occurrence."
    )
    allow_overlap_slots = fields.Boolean(
        default=False,
        help="If enabled, the generator won't skip when overlapping availability slots already exist."
    )
    conflict_policy = fields.Selection(
        [
            ("skip", "Skip on Conflicts"),
            ("soft", "Soft Warn (still create)"),
        ],
        default="skip",
        help="How to react to conflicts with room restrictions or appointments during generation."
    )

    # Preferred timezone for rule interpretation (optional)
    rule_tz = fields.Char(
        help="Timezone used to interpret start/end times and compute occurrences. "
             "Defaults to Doctor's User timezone, else Company timezone, else UTC."
    )

    color = fields.Integer(help="Color index for quick visual reference in list view.")

    # -------------------------------------------------------------------------
    # CONSTRAINTS & ONCHANGES
    # -------------------------------------------------------------------------
    @api.constrains("start_time", "end_time")
    def _check_time_window(self):
        for rec in self:
            if rec.start_time is None or rec.end_time is None:
                raise ValidationError(_("Start time and End time are required."))
            if rec.start_time < 0 or rec.start_time >= 24 or rec.end_time <= 0 or rec.end_time > 24:
                raise ValidationError(_("Start/End times must be within [0, 24] hours."))
            if rec.end_time <= rec.start_time:
                raise ValidationError(_("End time must be greater than Start time."))

    @api.constrains("slot_duration_min", "buffer_before_min", "buffer_after_min", "capacity_per_slot")
    def _check_positive_values(self):
        for rec in self:
            if rec.slot_duration_min <= 0:
                raise ValidationError(_("Slot duration must be a positive integer."))
            if rec.buffer_before_min < 0 or rec.buffer_after_min < 0:
                raise ValidationError(_("Buffers cannot be negative."))
            if rec.capacity_per_slot < 0:
                raise ValidationError(_("Capacity per slot cannot be negative. Use 0 to inherit doctor capacity."))

    @api.constrains("interval_weeks")
    def _check_interval_weeks(self):
        for rec in self:
            if rec.interval_weeks <= 0:
                raise ValidationError(_("Interval (weeks) must be at least 1."))

    @api.constrains("date_start", "date_end")
    def _check_date_range(self):
        for rec in self:
            if rec.date_start and rec.date_end and rec.date_end < rec.date_start:
                raise ValidationError(_("End date cannot be earlier than Start date."))

    @api.onchange("doctor_id", "weekday", "start_time", "end_time", "room_id", "telemedicine_only")
    def _onchange_autoname(self):
        for rec in self:
            if not rec.doctor_id or rec.start_time is None or rec.end_time is None:
                continue
            wd = dict(WEEKDAY_SELECTION).get(rec.weekday or "0", "Monday")
            label_room = rec.room_id.display_name if rec.room_id else _("No Room")
            label_mode = _("Telemedicine") if rec.telemedicine_only else _("Onsite")
            rec.name = _("%(doc)s — %(dow)s %(start)s–%(end)s (%(mode)s, %(room)s)") % {
                "doc": rec.doctor_id.display_name,
                "dow": wd,
                "start": rec._float_to_hhmm(rec.start_time),
                "end": rec._float_to_hhmm(rec.end_time),
                "mode": label_mode,
                "room": label_room,
            }

    # -------------------------------------------------------------------------
    # COMPUTES
    # -------------------------------------------------------------------------
    def _compute_next_occurrence(self):
        now_utc = fields.Datetime.now()
        for rec in self:
            nxt = rec._find_next_occurrence(start_from=now_utc)
            rec.next_occurrence_utc = nxt

    # -------------------------------------------------------------------------
    # TIMEZONE & TIME HELPERS
    # -------------------------------------------------------------------------
    def _get_rule_tzname(self):
        """Choose the timezone used to interpret start/end times."""
        self.ensure_one()
        # 1) explicit rule_tz
        if self.rule_tz:
            return self.rule_tz
        # 2) doctor's user tz
        if self.doctor_id and self.doctor_id.user_id and self.doctor_id.user_id.tz:
            return self.doctor_id.user_id.tz
        # 3) company tz
        if self.company_id and self.company_id.partner_id and self.company_id.partner_id.tz:
            return self.company_id.partner_id.tz
        # 4) fallback
        return "UTC"

    @staticmethod
    def _float_to_hhmm(value):
        """Convert 13.5 → '13:30'."""
        hours = int(value)
        minutes = int(round((value - hours) * 60.0))
        return f"{hours:02d}:{minutes:02d}"

    @staticmethod
    def _hhmm_to_float(hhmm):
        """Convert '13:30' → 13.5."""
        hh, mm = hhmm.split(":")
        return float(int(hh)) + float(int(mm)) / 60.0

    def _compose_occurrence_local(self, base_date):
        """
        Build localized datetimes from base_date (a date in local tz) + float times.
        Returns (dt_start_local, dt_end_local) in the rule tz (tz-aware).
        """
        self.ensure_one()
        tzname = self._get_rule_tzname()
        tz = timezone(tzname)

        start_h = int(self.start_time)
        start_m = int(round((self.start_time - start_h) * 60))
        end_h = int(self.end_time)
        end_m = int(round((self.end_time - end_h) * 60))

        dt_start_local = tz.localize(datetime(base_date.year, base_date.month, base_date.day, start_h, start_m, 0))
        dt_end_local = tz.localize(datetime(base_date.year, base_date.month, base_date.day, end_h, end_m, 0))
        return dt_start_local, dt_end_local

    # -------------------------------------------------------------------------
    # OCCURRENCE GENERATION
    # -------------------------------------------------------------------------
    def _iter_occurrences(self, date_from, date_to):
        """
        Yield (start_utc, end_utc) datetimes for every matching weekday between date_from and date_to
        observing interval_weeks and date_start/date_end boundaries.
        """
        self.ensure_one()
        if not date_from or not date_to:
            return
        if date_to < date_from:
            return

        # Guard by rule-level date range
        eff_start = self.date_start or date_from
        eff_end = self.date_end or date_to
        if eff_end < date_from or eff_start > date_to:
            return

        # align the first candidate date to the selected weekday
        wd_target = int(self.weekday)
        # Start iterating from max(date_from, date_start)
        cur = max(date_from, eff_start)

        # Move cur to the target weekday
        delta_days = (wd_target - cur.weekday()) % 7
        cur = cur + timedelta(days=delta_days)

        tzname = self._get_rule_tzname()
        tz = timezone(tzname)

        # Compute week span in days
        span_days = self.interval_weeks * 7

        while cur <= min(date_to, eff_end):
            # build local-aware datetimes, then convert to UTC
            dt_start_local, dt_end_local = self._compose_occurrence_local(cur)
            start_utc = dt_start_local.astimezone(UTC).replace(tzinfo=None)
            end_utc = dt_end_local.astimezone(UTC).replace(tzinfo=None)
            yield (start_utc, end_utc)
            cur = cur + timedelta(days=span_days)

    # -------------------------------------------------------------------------
    # CONFLICTS & POLICIES
    # -------------------------------------------------------------------------
    def _has_doctor_leave_conflict(self, start_utc, end_utc):
        """Return True if the doctor has a leave overlapping the [start,end] window."""
        if not self.skip_on_doctor_leave or "clinic.doctor.leave" not in self.env:
            return False
        Leave = self.env["clinic.doctor.leave"]
        return bool(Leave.search_count([
            ("doctor_id", "=", self.doctor_id.id),
            ("date_from", "<", end_utc),
            ("date_to", ">", start_utc),
        ], limit=1))

    def _has_calendar_leave_conflict(self, start_utc, end_utc):
        """Return True if the doctor's calendar has a leave overlapping the [start,end] window."""
        if not self.skip_on_calendar_leave:
            return False
        cal = self.doctor_id.calendar_id
        if not cal or "resource.calendar.leaves" not in self.env:
            return False
        CalLeave = self.env["resource.calendar.leaves"]
        return bool(CalLeave.search_count([
            ("calendar_id", "=", cal.id),
            ("date_from", "<", end_utc),
            ("date_to", ">", start_utc),
        ], limit=1))

    def _room_allows_specialty(self):
        """Check room's allowed_specialty_ids policy (if any)."""
        if not self.room_id:
            return True
        # room inheritance provided by clinic_doctor adds allowed_specialty_ids
        if "allowed_specialty_ids" in self.room_id._fields and self.room_id.allowed_specialty_ids:
            if self.specialty_id and self.specialty_id.id in self.room_id.allowed_specialty_ids.ids:
                return True
            # If rule has no specialty, allow by default (room-level filter only applies if explicit).
            return False if self.specialty_id else True
        return True

    def _find_existing_slot(self, start_utc, end_utc):
        """Find an existing availability slot with the exact same window."""
        if "clinic.availability.slot" not in self.env:
            return False
        Slot = self.env["clinic.availability.slot"]
        domain = [
            ("doctor_id", "=", self.doctor_id.id),
            ("start", "=", start_utc),
            ("end", "=", end_utc),
        ]
        if self.room_id:
            domain.append(("room_id", "=", self.room_id.id))
        return Slot.search(domain, limit=1)

    def _has_overlapping_slot(self, start_utc, end_utc):
        """Return True if there is any overlapping availability slot (any state)."""
        if "clinic.availability.slot" not in self.env:
            return False
        Slot = self.env["clinic.availability.slot"]
        domain = [
            ("doctor_id", "=", self.doctor_id.id),
            ("start", "<", end_utc),
            ("end", ">", start_utc),
        ]
        if self.room_id:
            domain.append(("room_id", "=", self.room_id.id))
        return bool(Slot.search_count(domain, limit=1))

    # def _has_overlapping_appointment(self, start_utc, end_utc):
    #     """Return True if an appointment overlaps the window (non-terminal states)."""
    #     if "clinic.appointment" not in self.env:
    #         return False
    #     App = self.env["clinic.appointment"]
    #     domain = [
    #         ("doctor_id", "=", self.doctor_id.id),
    #         ("state", "not in", ["canceled", "done", "no_show"]),
    #         ("start", "<", end_utc),
    #         ("end", ">", start_utc),
    #     ]
    #     if self.room_id and "room_id" in App._fields:
    #         domain.append(("room_id", "=", self.room_id.id))
    #     return bool(App.search_count(domain, limit=1))

    # -------------------------------------------------------------------------
    # SLOT MATERIALIZATION
    # -------------------------------------------------------------------------
    def _prepare_slot_vals(self, start_utc, end_utc):
        """Map rule → clinic.availability.slot create values."""
        self.ensure_one()
        capacity = self.capacity_per_slot or self.doctor_id.capacity_per_slot or 1
        vals = {
            "doctor_id": self.doctor_id.id,
            "start": start_utc,
            "end": end_utc,
            "capacity": capacity,
            "state": "open",  # default state
            "company_id": self.company_id.id,
            "telemedicine": self.telemedicine_only if "telemedicine" in self.env["clinic.availability.slot"]._fields else False,
        }
        if self.room_id and "room_id" in self.env["clinic.availability.slot"]._fields:
            vals["room_id"] = self.room_id.id
        if self.specialty_id and "specialty_id" in self.env["clinic.availability.slot"]._fields:
            vals["specialty_id"] = self.specialty_id.id
        # Optional buffers if slot model supports them
        Slot = self.env["clinic.availability.slot"]
        if "buffer_before_min" in Slot._fields:
            vals["buffer_before_min"] = self.buffer_before_min
        if "buffer_after_min" in Slot._fields:
            vals["buffer_after_min"] = self.buffer_after_min
        return vals

    def _materialize_occurrence(self, start_utc, end_utc, results):
        """
        Create a sequence of slots of length slot_duration_min within [start,end],
        respecting buffers. Append report entries to `results`.
        """
        if "clinic.availability.slot" not in self.env:
            results["skipped_missing_model"] += 1
            return

        # Conflict: leaves
        skip_leave = self._has_doctor_leave_conflict(start_utc, end_utc) or self._has_calendar_leave_conflict(start_utc, end_utc)
        if skip_leave:
            results["skipped_leave"] += 1
            return

        # Conflict: room specialty policy
        if not self._room_allows_specialty():
            if self.conflict_policy == "skip":
                results["skipped_room_restrict"] += 1
                return
            results["soft_conflicts"].append(_("Room restriction ignored (soft policy)."))

        # Existing identical slot
        if self._find_existing_slot(start_utc, end_utc):
            results["skipped_existing"] += 1
            return

        # Overlapping slots
        if not self.allow_overlap_slots and self._has_overlapping_slot(start_utc, end_utc):
            results["skipped_overlap_slot"] += 1
            return

        # Appointments overlapping (avoid generating open slots that collide)
        # if self.conflict_policy == "skip" and self._has_overlapping_appointment(start_utc, end_utc):
        #     results["skipped_overlap_appt"] += 1
        #     return

        # Build micro-slots (slot_duration_min segments)
        cur = start_utc
        delta = timedelta(minutes=self.slot_duration_min)
        Slot = self.env["clinic.availability.slot"].sudo()
        created = 0

        while cur < end_utc:
            cur_end = min(end_utc, cur + delta)
            vals = self._prepare_slot_vals(cur, cur_end)
            Slot.create(vals)
            created += 1
            cur = cur_end

        results["created"] += created

    # Public API
    def generate_slots(self, date_from=None, date_to=None):
        """
        Materialize availability slots for this rule between date_from and date_to (both inclusive).
        If not provided, defaults to [today .. today + 30 days].
        Returns a summary dict.
        """
        self.ensure_one()
        if not self.active:
            raise UserError(_("This rule is inactive."))

        if date_from is None or date_to is None:
            today = fields.Date.context_today(self)
            date_from = date_from or today
            date_to = date_to or (today + timedelta(days=30))

        if not isinstance(date_from, date):
            raise UserError(_("date_from must be a date."))
        if not isinstance(date_to, date):
            raise UserError(_("date_to must be a date."))
        if date_to < date_from:
            raise UserError(_("date_to cannot be earlier than date_from."))

        results = {
            "created": 0,
            "skipped_leave": 0,
            "skipped_existing": 0,
            "skipped_overlap_slot": 0,
            "skipped_overlap_appt": 0,
            "skipped_missing_model": 0,
            "skipped_room_restrict": 0,
            "soft_conflicts": [],
        }

        for start_utc, end_utc in self._iter_occurrences(date_from, date_to):
            self._materialize_occurrence(start_utc, end_utc, results)

        return results

    # Batch API
    def batch_generate_slots(self, date_from=None, date_to=None):
        """
        Generate slots for all selected rules and return an aggregate summary.
        """
        summary = {
            "created": 0,
            "skipped_leave": 0,
            "skipped_existing": 0,
            "skipped_overlap_slot": 0,
            "skipped_overlap_appt": 0,
            "skipped_missing_model": 0,
            "skipped_room_restrict": 0,
            "soft_conflicts": [],
            "rules": {},
        }
        for rec in self:
            res = rec.generate_slots(date_from=date_from, date_to=date_to)
            summary["rules"][rec.id] = res
            for k in ("created", "skipped_leave", "skipped_existing", "skipped_overlap_slot",
                      "skipped_overlap_appt", "skipped_missing_model", "skipped_room_restrict"):
                summary[k] += res[k]
            summary["soft_conflicts"] += res["soft_conflicts"]
        return summary

    # Cron-friendly method (context may pass window)
    def cron_generate_slots(self):
        """
        Called by scheduler/cron with context keys:
            ctx['date_from'] (date) and ctx['date_to'] (date)
        Falls back to [today .. today+30] if not provided.
        """
        ctx = self.env.context or {}
        date_from = ctx.get("date_from")
        date_to = ctx.get("date_to")

        # Convert from strings if necessary
        if isinstance(date_from, str):
            date_from = fields.Date.from_string(date_from)
        if isinstance(date_to, str):
            date_to = fields.Date.from_string(date_to)

        rules = self.search([("active", "=", True)])
        return rules.batch_generate_slots(date_from=date_from, date_to=date_to)

    # UX Actions
    def action_generate_slots(self):
        """
        UI button: Generate slots for a selected period (reads context date range).
        """
        self.ensure_one()
        ctx = self.env.context or {}
        date_from = ctx.get("date_from")
        date_to = ctx.get("date_to")
        if isinstance(date_from, str):
            date_from = fields.Date.from_string(date_from)
        if isinstance(date_to, str):
            date_to = fields.Date.from_string(date_to)

        res = self.generate_slots(date_from=date_from, date_to=date_to)
        # Notify user
        msg = _(
            "Slot generation completed.\n"
            "Created: %(c)s\n"
            "Skipped (leave): %(l)s\n"
            "Skipped (existing): %(e)s\n"
            "Skipped (overlap slot): %(os)s\n"
            "Skipped (overlap appt): %(oa)s\n"
            "Skipped (missing model): %(mm)s\n"
            "Skipped (room restrict): %(rr)s\n"
            "Notes: %(notes)s",
            c=res["created"], l=res["skipped_leave"], e=res["skipped_existing"],
            os=res["skipped_overlap_slot"], oa=res["skipped_overlap_appt"],
            mm=res["skipped_missing_model"], rr=res["skipped_room_restrict"],
            notes=", ".join(res["soft_conflicts"]) or "-",
        )
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {"title": _("Schedule Rule"), "message": msg, "sticky": False},
        }

    def action_view_generated_slots(self):
        """Open generated availability slots filtered by this rule's dimensions."""
        self.ensure_one()
        if "clinic.availability.slot" not in self.env:
            return {
                "type": "ir.actions.client",
                "tag": "display_notification",
                "params": {"title": _("Not Available"),
                           "message": _("Availability model is not installed."),
                           "sticky": False},
            }
        domain = [("doctor_id", "=", self.doctor_id.id)]
        if self.room_id and "room_id" in self.env["clinic.availability.slot"]._fields:
            domain.append(("room_id", "=", self.room_id.id))
        if self.specialty_id and "specialty_id" in self.env["clinic.availability.slot"]._fields:
            domain.append(("specialty_id", "=", self.specialty_id.id))
        return {
            "type": "ir.actions.act_window",
            "name": _("Availability"),
            "res_model": "clinic.availability.slot",
            "view_mode": "calendar,list,form",
            "domain": domain,
            "target": "current",
        }

    # -------------------------------------------------------------------------
    # NEXT OCCURRENCE FINDER
    # -------------------------------------------------------------------------
    def _find_next_occurrence(self, start_from=None):
        """
        Return the next occurrence datetime in UTC (start) after start_from (UTC naive),
        or False if none (due to date_end or inactive).
        """
        self.ensure_one()
        if not self.active:
            return False

        start_from = start_from or fields.Datetime.now()
        base_date = start_from.date()
        # Iterate up to a reasonable horizon (1 year) for safety
        horizon = base_date + timedelta(days=365)
        for start_utc, _end_utc in self._iter_occurrences(base_date, horizon):
            if start_utc >= start_from:
                return start_utc
        return False
