from odoo import api, fields, models, _
from odoo.exceptions import AccessError, UserError, ValidationError


class ClinicL10nIdNumberingPolicy(models.Model):
    """Safe governance over native Odoo journal sequence-prefix configuration."""

    _name = "clinic.l10n.id.numbering.policy"
    _description = "Clinic Indonesia Invoice Numbering Policy"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _order = "company_id, journal_id, id"
    _check_company_auto = True

    _journal_unique = models.Constraint(
        "UNIQUE(journal_id)",
        "Only one Clinic Indonesia numbering policy is allowed per journal.",
    )
    _company_state_idx = models.Index("(company_id, state)")

    name = fields.Char(compute="_compute_name", store=True)
    profile_id = fields.Many2one(
        "clinic.l10n.id.tax.profile",
        required=True,
        check_company=True,
        ondelete="cascade",
        domain="[('company_id', '=', company_id)]",
    )
    company_id = fields.Many2one(
        "res.company",
        required=True,
        default=lambda self: self.env.company,
        index=True,
    )
    journal_id = fields.Many2one(
        "account.journal",
        required=True,
        check_company=True,
        ondelete="restrict",
        domain="[('company_id', '=', company_id), ('type', 'in', ('sale', 'purchase'))]",
        tracking=True,
    )
    journal_type = fields.Selection(related="journal_id.type", store=True, readonly=True)
    current_code = fields.Char(related="journal_id.code", readonly=True)
    # Odoo journal.code is the native sequence prefix; this policy governs it instead of inventing a second numbering engine.
    expected_code = fields.Char(
        string="Expected Sequence Prefix",
        required=True,
        size=5,
        tracking=True,
        help="Odoo 19 journal code is the native default prefix for entries generated by this journal.",
    )
    dedicated_credit_note_sequence = fields.Boolean(
        default=True,
        tracking=True,
    )
    secure_posted_entries = fields.Boolean(
        string="Secure Posted Entries with Hash",
        default=False,
        tracking=True,
        help="Applies the native Odoo journal secure-posted-entry option. Use only after accounting governance review.",
    )
    native_sequence_override_regex = fields.Text(
        related="journal_id.sequence_override_regex",
        readonly=True,
        string="Native Sequence Override Regex",
    )

    state = fields.Selection(
        [
            ("draft", "Draft"),
            ("validated", "Validated"),
            ("applied", "Applied"),
            ("archived", "Archived"),
        ],
        default="draft",
        required=True,
        tracking=True,
        index=True,
    )
    posted_move_count = fields.Integer(compute="_compute_posted_move_count")
    # The enterprise search view filters Numbering Policies by compliance.
    # A computed field used in a domain must be stored or implement a search method.
    compliant = fields.Boolean(
        compute="_compute_compliant",
        store=True,
        index=True,
    )
    compliance_note = fields.Char(compute="_compute_compliant")
    applied_at = fields.Datetime(readonly=True)
    applied_by_id = fields.Many2one("res.users", readonly=True)
    note = fields.Text()

    @api.depends("journal_id", "expected_code")
    def _compute_name(self):
        for record in self:
            record.name = _("%s Numbering Policy") % (
                record.journal_id.display_name or record.expected_code or _("Journal")
            )

    def _compute_posted_move_count(self):
        Move = self.env["account.move"]
        for record in self:
            record.posted_move_count = (
                Move.search_count([
                    ("journal_id", "=", record.journal_id.id),
                    ("state", "=", "posted"),
                ])
                if record.journal_id
                else 0
            )

    @api.depends(
        "journal_id.code",
        "journal_id.refund_sequence",
        "journal_id.restrict_mode_hash_table",
        "expected_code",
        "dedicated_credit_note_sequence",
        "secure_posted_entries",
    )
    def _compute_compliant(self):
        for record in self:
            if not record.journal_id:
                record.compliant = False
                record.compliance_note = _("Journal is not configured.")
                continue

            mismatches = []
            if record.journal_id.code != record.expected_code:
                mismatches.append(_("sequence prefix"))
            if record.journal_id.refund_sequence != record.dedicated_credit_note_sequence:
                mismatches.append(_("credit-note sequence"))
            if bool(record.journal_id.restrict_mode_hash_table) != bool(record.secure_posted_entries):
                mismatches.append(_("secure-entry setting"))

            record.compliant = not mismatches
            record.compliance_note = (
                _("Native journal matches the policy.")
                if not mismatches
                else _("Mismatch: %s") % ", ".join(mismatches)
            )

    @api.onchange("profile_id")
    def _onchange_profile(self):
        for record in self:
            if record.profile_id:
                record.company_id = record.profile_id.company_id

    @api.onchange("journal_id")
    def _onchange_journal(self):
        for record in self:
            if record.journal_id:
                record.company_id = record.journal_id.company_id
                if not record.expected_code:
                    record.expected_code = record.journal_id.code

    @api.constrains("profile_id", "company_id", "journal_id")
    def _check_scope(self):
        for record in self:
            if record.profile_id.company_id != record.company_id:
                raise ValidationError(_("Numbering Policy and Tax Profile company must match."))
            if record.journal_id.company_id != record.company_id:
                raise ValidationError(_("Numbering Policy and Journal company must match."))

    def write(self, vals):
        governed_fields = {
            "profile_id",
            "company_id",
            "journal_id",
            "expected_code",
            "dedicated_credit_note_sequence",
            "secure_posted_entries",
        }
        system_fields = {"state", "applied_at", "applied_by_id"}

        if system_fields.intersection(vals) and not self.env.context.get("l10n_transition"):
            raise AccessError(_("Numbering workflow and application audit fields are controlled by policy actions."))

        if governed_fields.intersection(vals):
            for record in self:
                if record.state not in ("draft", "validated"):
                    raise UserError(_("Applied/Archived numbering policies cannot be edited."))
        return super().write(vals)

    def action_validate(self):
        self._manager_required()
        for record in self:
            if not record.expected_code:
                raise UserError(_("Expected Sequence Prefix is required."))
            if len(record.expected_code) > 5:
                raise UserError(_("Odoo journal sequence prefix cannot exceed five characters."))
            if record.journal_id.type not in ("sale", "purchase"):
                raise UserError(_("Invoice Numbering Policy supports Sales and Purchase journals only."))
            record.with_context(l10n_transition=True).write({"state": "validated"})
        return True

    # Posted numbering evidence is immutable: once posting starts, policy mismatches become review items rather than silent mutations.
    def action_apply(self):
        self._manager_required()
        for record in self:
            if record.state != "validated":
                raise UserError(_("Validate the Numbering Policy before applying it."))

            posted_count = self.env["account.move"].search_count([
                ("journal_id", "=", record.journal_id.id),
                ("state", "=", "posted"),
            ])

            # Posted invoice numbers are immutable accounting evidence. ClinicOne
            # never rewrites them and will not silently change a prefix after the
            # journal already has posted entries.
            if posted_count and not record.compliant:
                raise UserError(_(
                    "Journal %s already has %s posted entries and its native numbering/security "
                    "configuration does not match this policy. ClinicOne will not mutate journal "
                    "sequence controls after posting has started. Use the policy as audit evidence "
                    "and perform a formal accounting review."
                ) % (
                    record.journal_id.display_name,
                    posted_count,
                ))

            if not posted_count:
                record.journal_id.write({
                    "code": record.expected_code,
                    "refund_sequence": record.dedicated_credit_note_sequence,
                    "restrict_mode_hash_table": record.secure_posted_entries,
                })
            record.with_context(l10n_transition=True).write({
                "state": "applied",
                "applied_at": fields.Datetime.now(),
                "applied_by_id": self.env.user.id,
            })
        return True

    def action_archive(self):
        self._manager_required()
        self.with_context(l10n_transition=True).write({"state": "archived"})
        return True

    def action_reset_to_draft(self):
        self._manager_required()
        for record in self:
            if record.state == "applied":
                raise UserError(
                    _("An Applied policy is audit evidence. Create a replacement policy instead of resetting it.")
                )
            record.with_context(l10n_transition=True).write({"state": "draft"})
        return True

    def _manager_required(self):
        if not self.env.user.has_group("clinic_l10n_id.group_clinic_l10n_id_manager"):
            raise AccessError(_("Only an Indonesia Localization Manager can govern invoice numbering."))

    def action_open_journal(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Odoo Accounting Journal"),
            "res_model": "account.journal",
            "view_mode": "form",
            "res_id": self.journal_id.id,
        }

    def action_open_posted_moves(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Posted Journal Entries"),
            "res_model": "account.move",
            "view_mode": "list,form",
            "domain": [
                ("journal_id", "=", self.journal_id.id),
                ("state", "=", "posted"),
            ],
        }

