import base64
import csv
import io
import logging
import re
from datetime import datetime

from odoo import api, fields, models, _
from odoo.exceptions import AccessError, UserError, ValidationError


_logger = logging.getLogger(__name__)


ENGINE_METHODS = {
    "fin_revenue": "_generate_fin_revenue",
    "fin_receivables": "_generate_fin_receivables",
    "fin_payables": "_generate_fin_payables",
    "fin_cashflow": "_generate_fin_cashflow",
    "fin_accounting": "_generate_fin_accounting",
    "fin_tax": "_generate_fin_tax",
    "fin_insurance": "_generate_fin_insurance",
    "ops_booking": "_generate_ops_booking",
    "ops_queue": "_generate_ops_queue",
    "ops_room": "_generate_ops_room",
    "ops_inventory": "_generate_ops_inventory",
    "ops_membership": "_generate_ops_membership",
    "ops_wallet": "_generate_ops_wallet",
    "clinical_encounter": "_generate_clinical_encounter",
    "clinical_procedure": "_generate_clinical_procedure",
    "clinical_triage": "_generate_clinical_triage",
    "clinical_adverse": "_generate_clinical_adverse",
    "clinical_postcare": "_generate_clinical_postcare",
    "clinical_feedback": "_generate_clinical_feedback",
}


class ClinicReportRun(models.Model):
    """Governed report execution and immutable finalized snapshot."""

    _name = "clinic.report.run"
    _description = "Clinic Report Run"
    _inherit = [
        "mail.thread",
        "mail.activity.mixin",
        "clinic.report.company.mixin",
        "clinic.report.engine.financial",
        "clinic.report.engine.operational",
        "clinic.report.engine.clinical",
    ]
    _order = "date_to desc, generated_at desc, id desc"
    _check_company_auto = True

    _name_company_unique = models.Constraint(
        "UNIQUE(company_id, name)",
        "Report Run reference must be unique per company.",
    )
    _date_order_valid = models.Constraint(
        "CHECK(date_to >= date_from)",
        "Report end date must be on or after the start date.",
    )
    _company_state_idx = models.Index("(company_id, state, date_from, date_to)")
    _definition_date_idx = models.Index("(definition_id, date_from, date_to, state)")

    name = fields.Char(
        default="/",
        readonly=True,
        copy=False,
        index=True,
        tracking=True,
    )
    schedule_id = fields.Many2one(
        "clinic.report.schedule",
        string="Generated By Schedule",
        readonly=True,
        copy=False,
        ondelete="set null",
        index=True,
    )
    definition_id = fields.Many2one(
        "clinic.report.definition",
        required=True,
        ondelete="restrict",
        index=True,
        tracking=True,
        domain="[('state', '=', 'active')]",
    )
    family = fields.Selection(
        related="definition_id.family",
        store=True,
        readonly=True,
        index=True,
    )
    report_key = fields.Selection(
        related="definition_id.report_key",
        store=True,
        readonly=True,
        index=True,
    )

    date_from = fields.Date(required=True, tracking=True, index=True)
    date_to = fields.Date(required=True, tracking=True, index=True)
    include_details = fields.Boolean(default=True)
    detail_limit = fields.Integer(default=500)

    currency_id = fields.Many2one(
        related="company_id.currency_id",
        store=True,
        readonly=True,
    )

    state = fields.Selection(
        [
            ("draft", "Draft"),
            ("generating", "Generating"),
            ("ready", "Ready"),
            ("failed", "Failed"),
            ("finalized", "Finalized"),
            ("archived", "Archived"),
        ],
        default="draft",
        required=True,
        tracking=True,
        index=True,
    )

    generated_at = fields.Datetime(readonly=True, index=True)
    generated_by_id = fields.Many2one("res.users", readonly=True)
    finalized_at = fields.Datetime(readonly=True)
    finalized_by_id = fields.Many2one("res.users", readonly=True)
    error_message = fields.Text(readonly=True)
    methodology_snapshot = fields.Html(readonly=True, sanitize=True)

    metric_ids = fields.One2many(
        "clinic.report.metric",
        "run_id",
        string="Metrics",
        copy=False,
    )
    detail_ids = fields.One2many(
        "clinic.report.detail",
        "run_id",
        string="Details",
        copy=False,
    )
    metric_count = fields.Integer(compute="_compute_counts")
    detail_count = fields.Integer(compute="_compute_counts")

    csv_file = fields.Binary(readonly=True, copy=False)
    csv_filename = fields.Char(readonly=True, copy=False)

    notes = fields.Text()

    @api.model_create_multi
    def create(self, vals_list):
        prepared = []
        for original in vals_list:
            vals = dict(original)
            company = self.env["res.company"].browse(
                vals.get("company_id")
            ) or self.env.company

            if vals.get("name") in (False, "/"):
                vals["name"] = (
                    self.env["ir.sequence"]
                    .with_company(company)
                    .next_by_code("clinic.report.run")
                    or "/"
                )

            definition = self.env["clinic.report.definition"].browse(
                vals.get("definition_id")
            )
            if definition.exists():
                vals.setdefault("include_details", definition.include_details_by_default)
                vals.setdefault("detail_limit", definition.default_detail_limit)

            prepared.append(vals)

        return super().create(prepared)

    @api.constrains("detail_limit")
    def _check_detail_limit(self):
        for record in self:
            if not 1 <= record.detail_limit <= 10000:
                raise ValidationError(
                    _("Report Detail Limit must be between 1 and 10,000 rows.")
                )

    @api.constrains("definition_id", "branch_id")
    def _check_definition_branch(self):
        for record in self:
            if (
                record.branch_id
                and record.definition_id
                and not record.definition_id.allow_branch_filter
            ):
                raise ValidationError(
                    _("This Report Definition does not support branch filtering.")
                )

    @api.depends("metric_ids", "detail_ids")
    def _compute_counts(self):
        for record in self:
            record.metric_count = len(record.metric_ids)
            record.detail_count = len(record.detail_ids)

    def write(self, vals):
        protected = {
            "definition_id",
            "company_id",
            "branch_id",
            "date_from",
            "date_to",
            "include_details",
            "detail_limit",
        }
        audit_fields = {
            "state",
            "generated_at",
            "generated_by_id",
            "finalized_at",
            "finalized_by_id",
            "error_message",
            "methodology_snapshot",
            "csv_file",
            "csv_filename",
        }
        if audit_fields.intersection(vals) and not self.env.context.get(
            "report_run_transition"
        ):
            raise AccessError(
                _("Use Report Run workflow actions to change status/audit output.")
            )

        for record in self:
            if record.state in ("finalized", "archived") and protected.intersection(vals):
                raise AccessError(
                    _("Finalized/Archived Report scope is immutable.")
                )

        return super().write(vals)

    def unlink(self):
        if self.filtered(lambda rec: rec.state in ("finalized", "archived")):
            raise AccessError(
                _("Finalized/Archived Report Runs cannot be deleted.")
            )
        return super().unlink()

    def _metric_code(self, code):
        return re.sub(r"[^A-Z0-9_]+", "_", (code or "").upper()).strip("_")[:64]

    # Normalized Metrics are the stable read layer for the later Dashboard addon.
    def _add_metric(
        self,
        code,
        name,
        value,
        metric_type="number",
        sequence=10,
        note=None,
    ):
        self.ensure_one()
        Metric = self.env["clinic.report.metric"].sudo().with_context(report_generation=True)
        normalized_code = self._metric_code(code)
        values = {
            "run_id": self.id,
            "sequence": sequence,
            "code": normalized_code,
            "name": name,
            "metric_type": metric_type,
            "value": float(value or 0.0),
            "note": note,
        }
        runtime = self.env.context.get("report_runtime")
        if runtime is not None and "metric_codes" in runtime:
            if normalized_code in runtime["metric_codes"]:
                raise UserError(_("Duplicate generated metric code: %s") % normalized_code)
            runtime["metric_codes"].add(normalized_code)
            # Stable (run, code) identity preserves downstream snapshot links.
            existing = Metric.search([("run_id", "=", self.id), ("code", "=", normalized_code)])
            if existing:
                existing.ensure_one()
                existing.write(values)
                return existing
        return Metric.create(values)


    def _as_datetime(self, value):
        if not value:
            return False
        if isinstance(value, datetime):
            return value
        try:
            date_value = fields.Date.to_date(value)
            return datetime.combine(date_value, datetime.min.time())
        except Exception:
            return fields.Datetime.to_datetime(value)

    # Detail snapshots keep source IDs for audit drill-down without taking source ownership.
    def _add_detail(
        self,
        source,
        label,
        event_date=None,
        reference=None,
        state_label=None,
        partner=None,
        patient=None,
        doctor=None,
        staff=None,
        treatment=None,
        room=None,
        amount=0.0,
        quantity=0.0,
        duration_minutes=0.0,
        rating=0.0,
        note=None,
        sequence=10,
    ):
        self.ensure_one()
        if not self.include_details:
            return self.env["clinic.report.detail"]

        # During one engine execution we carry a tiny mutable counter in
        # context.  This enforces Detail Limit without running COUNT(*) for
        # every row and without relying on a cached computed One2many count.
        runtime = self.env.context.get("report_runtime")
        if runtime is not None and runtime.get("detail_count", 0) >= self.detail_limit:
            return self.env["clinic.report.detail"]

        source_model = source._name if source else False
        source_res_id = source.id if source else False

        vals = {
            "run_id": self.id,
            "sequence": sequence,
            "event_date": self._as_datetime(event_date),
            "reference": reference or (
                source.display_name if source and "display_name" in source._fields else False
            ),
            "label": label,
            "state_label": state_label or "",
            "source_model": source_model,
            "source_res_id": source_res_id,
            "source_display_name": (
                source.display_name
                if source and "display_name" in source._fields
                else label
            ),
            "partner_id": partner.id if partner else False,
            "patient_id": patient.id if patient else False,
            "doctor_id": doctor.id if doctor else False,
            "staff_id": staff.id if staff else False,
            "treatment_id": treatment.id if treatment else False,
            "room_id": room.id if room else False,
            "amount": float(amount or 0.0),
            "quantity": float(quantity or 0.0),
            "duration_minutes": float(duration_minutes or 0.0),
            "rating": float(rating or 0.0),
            "note": note,
        }
        detail = self.env["clinic.report.detail"].sudo().with_context(
            report_generation=True
        ).create(vals)
        if runtime is not None:
            runtime["detail_count"] = runtime.get("detail_count", 0) + 1
        return detail

    def _state_breakdown_metrics(self, records, prefix, start_sequence=100):
        self.ensure_one()
        counts = {}
        for record in records:
            key = record.state or "undefined"
            counts[key] = counts.get(key, 0) + 1

        for index, key in enumerate(sorted(counts)):
            self._add_metric(
                f"{prefix}_{key}",
                _("Status: %s") % key.replace("_", " ").title(),
                counts[key],
                metric_type="count",
                sequence=start_sequence + index,
            )

    def _percentage(self, numerator, denominator):
        return (float(numerator) / float(denominator) * 100.0) if denominator else 0.0

    # CSV is generated from the same governed snapshot shown in Odoo/PDF, avoiding a second KPI engine.
    def _refresh_csv(self):
        self.ensure_one()
        stream = io.StringIO()
        writer = csv.writer(stream)
        writer.writerow([
            "Run",
            "Report",
            "Family",
            "Company",
            "Branch",
            "Date From",
            "Date To",
        ])
        writer.writerow([
            self.name,
            self.definition_id.name,
            self.family,
            self.company_id.display_name,
            self.branch_id.display_name if self.branch_id else "",
            self.date_from,
            self.date_to,
        ])
        writer.writerow([])
        writer.writerow(["METRICS"])
        writer.writerow(["Code", "Metric", "Type", "Value", "Display", "Note"])
        for metric in self.metric_ids.sorted("sequence"):
            writer.writerow([
                metric.code,
                metric.name,
                metric.metric_type,
                metric.value,
                metric.display_value,
                metric.note or "",
            ])

        writer.writerow([])
        writer.writerow(["DETAILS"])
        writer.writerow([
            "Date",
            "Reference",
            "Label",
            "Status",
            "Patient",
            "Doctor",
            "Staff",
            "Treatment",
            "Room",
            "Amount",
            "Quantity",
            "Duration Minutes",
            "Rating",
            "Source Model",
            "Source ID",
            "Note",
        ])
        for detail in self.detail_ids.sorted(
            key=lambda row: (row.event_date or fields.Datetime.now(), row.id)
        ):
            writer.writerow([
                detail.event_date or "",
                detail.reference or "",
                detail.label,
                detail.state_label or "",
                detail.patient_id.display_name if detail.patient_id else (
                    detail.partner_id.display_name if detail.partner_id else ""
                ),
                detail.doctor_id.display_name if detail.doctor_id else "",
                detail.staff_id.display_name if detail.staff_id else "",
                detail.treatment_id.display_name if detail.treatment_id else "",
                detail.room_id.display_name if detail.room_id else "",
                detail.amount,
                detail.quantity,
                detail.duration_minutes,
                detail.rating,
                detail.source_model or "",
                detail.source_res_id or "",
                detail.note or "",
            ])

        content = stream.getvalue().encode("utf-8-sig")
        filename = f"{self.name.replace('/', '-')}_{self.report_key}.csv"
        self.with_context(report_run_transition=True).write({
            "csv_file": base64.b64encode(content),
            "csv_filename": filename,
        })

    # Generation uses controlled sudo reads only after explicit company/date/branch scoping; source rows are never mutated.
    def action_generate(self):
        self._reports_require_group(
            "clinic_reports.group_reports_analyst",
            _("Only a Reports Analyst can generate reports."),
        )

        for run in self:
            if run.definition_id.state != "active":
                raise UserError(_("The selected Report Definition is not Active."))
            if run.state == "finalized":
                raise UserError(_("Finalized Reports cannot be regenerated."))
            if run.state == "archived":
                raise UserError(_("Archived Reports cannot be regenerated."))

            method_name = ENGINE_METHODS.get(run.report_key)
            if not method_name or not hasattr(run, method_name):
                raise UserError(
                    _("No reporting engine is registered for %s.") % run.report_key
                )

            run.with_context(report_run_transition=True).write({
                "state": "generating",
                "error_message": False,
                "methodology_snapshot": run.definition_id.methodology,
            })

            try:
                with self.env.cr.savepoint():
                    run.detail_ids.sudo().with_context(report_generation=True).unlink()
                    runtime = {"detail_count": 0, "metric_codes": set()}
                    getattr(
                        run.with_context(report_runtime=runtime),
                        method_name,
                    )()
                    # Remove obsolete codes only; FK restrictions still protect
                    # historical consumers if an engine removes a referenced KPI.
                    obsolete = run.metric_ids.filtered(lambda metric: metric.code not in runtime["metric_codes"])
                    obsolete.sudo().with_context(report_generation=True).unlink()
                    run.invalidate_recordset(
                        ["metric_ids", "detail_ids", "metric_count", "detail_count"]
                    )
                    run._refresh_csv()

                run.with_context(report_run_transition=True).write({
                    "state": "ready",
                    "generated_at": fields.Datetime.now(),
                    "generated_by_id": self.env.user.id,
                    "error_message": False,
                })
            except Exception as exc:
                _logger.exception(
                    "ClinicOne report generation failed for run %s",
                    run.display_name,
                )
                run.with_context(report_run_transition=True).write({
                    "state": "failed",
                    "error_message": str(exc),
                })
                return {
                    "type": "ir.actions.client",
                    "tag": "display_notification",
                    "params": {
                        "title": _("Report Generation Failed"),
                        "message": str(exc),
                        "type": "danger",
                        "sticky": True,
                    },
                }

        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Report Generated"),
                "message": _("The report snapshot and export are ready."),
                "type": "success",
                "sticky": False,
            },
        }

    # Finalization is a governance boundary: scope and generated output become immutable history.
    def action_finalize(self):
        self._reports_require_group(
            "clinic_reports.group_reports_manager",
            _("Only a Reports Manager can finalize reports."),
        )
        for run in self:
            if run.state != "ready":
                raise UserError(_("Only Ready reports can be finalized."))
            run.with_context(report_run_transition=True).write({
                "state": "finalized",
                "finalized_at": fields.Datetime.now(),
                "finalized_by_id": self.env.user.id,
            })
        return True

    def action_reset_to_draft(self):
        self._reports_require_group(
            "clinic_reports.group_reports_analyst",
            _("Only a Reports Analyst can reset a report."),
        )
        for run in self:
            if run.state not in ("ready", "failed"):
                raise UserError(_("Only Ready/Failed reports can return to Draft."))
            run.with_context(report_run_transition=True).write({
                "state": "draft",
                "error_message": False,
            })
        return True

    def action_archive(self):
        self._reports_require_group(
            "clinic_reports.group_reports_manager",
            _("Only a Reports Manager can archive reports."),
        )
        for run in self:
            if run.state != "finalized":
                raise UserError(_("Finalize the Report before archiving it."))
            run.with_context(report_run_transition=True).write({"state": "archived"})
        return True

    def action_view_metrics(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Report Metrics"),
            "res_model": "clinic.report.metric",
            "view_mode": "list,form,pivot,graph",
            "domain": [("run_id", "=", self.id)],
            "context": {"default_run_id": self.id},
        }

    def action_view_details(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Report Details"),
            "res_model": "clinic.report.detail",
            "view_mode": "list,form,pivot,graph",
            "domain": [("run_id", "=", self.id)],
            "context": {"default_run_id": self.id},
        }

    # Export never re-queries source transactions; it exports the current Report Run snapshot.
    def action_download_csv(self):
        self.ensure_one()
        if not self.csv_file:
            self._refresh_csv()
        return {
            "type": "ir.actions.act_url",
            "url": (
                f"/web/content/clinic.report.run/{self.id}/csv_file/"
                f"{self.csv_filename}?download=true"
            ),
            "target": "self",
        }

    def action_print_pdf(self):
        self.ensure_one()
        return self.env.ref(
            "clinic_reports.action_report_clinic_report_run"
        ).report_action(self)

