# -*- coding: utf-8 -*-
{
    "name": "ClinicOne - Electronic Medication Administration Record",
    "summary": "Enterprise prescriptions, medication orders, schedules, administrations, safety alerts, inventory and billing integration.",
    "version": "19.0.3.0.2",
    "category": "Clinic/Clinical",
    "author": "ClinicOne",
    "license": "LGPL-3",
    "application": True,
    "installable": True,
    "auto_install": False,
    "depends": [
        "base",
        "base_setup",
        "mail",
        "contacts",
        "hr",
        "account",
        "product",
        "stock",
        "sales_team",
        "uom",
        "clinic_base",
        "clinic_staff",
        "clinic_room_device",
        "clinic_treatment_catalog",
        "clinic_patient",
        "clinic_doctor",
        "clinic_queue_room",
        "clinic_inventory",
        "clinic_booking",
        "clinic_triage_vitals",
        "clinic_consent_legal",
        "clinic_encounter",
    ],
    "data": [
        "security/emar_security.xml",
        "security/ir.model.access.csv",
        "security/emar_rules.xml",
        "data/emar_sequence.xml",
        "data/emar_cron.xml",
        "wizard/emar_reschedule_wizard_views.xml",
        "views/emar_medication_profile_views.xml",
        "views/emar_prescription_views.xml",
        "views/emar_medication_line_views.xml",
        "views/emar_order_views.xml",
        "views/emar_schedule_views.xml",
        "views/emar_administration_views.xml",
        "views/emar_alert_views.xml",
        "views/emar_config_views.xml",
        "views/emar_menu_views.xml",
    ],
}
