

# -*- coding: utf-8 -*-
# ClinicOne — Clinical Staff (Nurse & Therapist) Management
# File: clinic_staff/models/practitioner.py
#
# Model "clinic.practitioner" dipakai lintas modul (mis. clinic_care_plan: m2m ke practitioner).
# Disusun CE-safe: tanpa hard dependency ke modul Enterprise. Integrasi ke modul lain dilakukan
# secara longgar (env.get, optional domains, compute toleran jika model lain belum terpasang).

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError
from datetime import date, datetime, timedelta


class ClinicPractitioner(models.Model):
    _name = "clinic.practitioner"
    _description = "Clinical Practitioner"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _rec_name = "display_name"
    _order = "active desc, name, id"

    # --------------------------
    # Identity & core attributes
    # --------------------------
    active = fields.Boolean(
        string="Active",
        default=True,
        tracking=True,
        help="If unchecked, the practitioner is hidden from operational pickers."
    )
    code = fields.Char(
        string="Practitioner Code",
        copy=False,
        index=True,
        help="Unique code generated by sequence for internal reference."
    )
    name = fields.Char(
        string="Practitioner Name",
        required=True,
        tracking=True,
        help="Public display name of the practitioner. By default copied from linked staff."
    )
    display_name = fields.Char(
        string="Display Name",
        compute="_compute_display_name",
        store=True,
        help="Readable label combining code, name, and specialty."
    )
    company_id = fields.Many2one(
        "res.company",
        string="Company",
        default=lambda s: s.env.company,
        index=True
    )
    branch_id = fields.Many2one(
        "clinic.branch",
        string="Branch",
        help="Operational branch of this practitioner.",
        tracking=True
    )

    # --------------------------
    # Links to staff & HR
    # --------------------------
    staff_id = fields.Many2one(
        "clinic.staff",
        string="Linked Staff",
        required=True,
        ondelete="restrict",
        index=True,
        tracking=True,
        help="Underlying staff record for this practitioner."
    )
    # CE-safe relateds: gunakan compute agar aman jika field di clinic.staff tidak tersedia
    employee_id = fields.Many2one(
        "hr.employee",
        string="Employee",
        compute="_compute_employee_partner_role",
        store=True,
        readonly=True
    )
    partner_id = fields.Many2one(
        "res.partner",
        string="Contact",
        compute="_compute_employee_partner_role",
        store=True,
        readonly=True
    )
    role = fields.Selection(
        selection=[
            ("doctor", "Doctor"),
            ("nurse", "Nurse"),
            ("therapist", "Therapist"),
            ("other", "Other"),
        ],
        string="Role",
        compute="_compute_employee_partner_role",
        store=True,
        readonly=True,
        help="Practitioner professional role (copied from staff if available)."
    )

    # --------------------------
    # Professional profile
    # --------------------------
    specialty = fields.Char(
        string="Specialty",
        help="Free-text specialty (e.g., Dermatology, Aesthetic Nurse, Physiotherapy)."
    )
    grade = fields.Char(
        string="Grade/Level",
        help="Professional grade or level (e.g., Senior Therapist, Junior Nurse)."
    )
    language_skills = fields.Char(
        string="Language Skills",
        help="Comma-separated language skills for patient matching."
    )
    experience_years = fields.Integer(
        string="Experience (Years)",
        default=0,
        help="Total years of professional experience."
    )

    # Skills (links to skill taxonomy defined in clinic_staff)
    skill_ids = fields.Many2many(
        "clinic.skill",
        "clinic_practitioner_skill_rel",
        "practitioner_id",
        "skill_id",
        string="Skills",
        help="Practitioner's skills for assignment eligibility."
    )

    # --------------------------
    # License & compliance
    # --------------------------
    license_valid_until = fields.Date(
        string="License Valid Until",
        compute="_compute_compliance",
        store=True,
        help="Latest validity date among active licenses linked via staff."
    )
    is_license_compliant = fields.Boolean(
        string="License Compliant",
        compute="_compute_compliance",
        store=True,
        help="True if the practitioner has at least one active/non-expired license."
    )
    compliance_notes = fields.Char(
        string="Compliance Notes",
        help="Optional notes regarding compliance (e.g., missing documents)."
    )

    # --------------------------
    # Operational readiness
    # --------------------------
    is_ready_for_assignment = fields.Boolean(
        string="Ready for Assignment",
        compute="_compute_readiness",
        store=True,
        help="True if active, license-compliant, and (optionally) currently present/available."
    )
    next_available_from = fields.Datetime(
        string="Next Available From",
        compute="_compute_readiness",
        help="Hint: the next datetime from which the practitioner is expected to be available."
    )

    # --------------------------
    # KPIs (soft integration)
    # --------------------------
    assignment_count = fields.Integer(
        string="Assignments",
        compute="_compute_counts",
        help="Total number of assignments linked to this practitioner."
    )
    availability_count = fields.Integer(
        string="Availability Slots",
        compute="_compute_counts",
        help="Total number of availability slots from linked staff."
    )
    license_count = fields.Integer(
        string="Licenses",
        compute="_compute_counts",
        help="Total number of licenses from linked staff."
    )
    roster_count = fields.Integer(
        string="Roster Lines",
        compute="_compute_counts",
        help="Total roster lines from linked staff."
    )

    image_1920 = fields.Image(
        string="Photo",
        max_width=1920,
        max_height=1920,
        help="Practitioner portrait."
    )

    notes = fields.Text(string="Notes")

    _code_company_uniq = models.Constraint(
        'unique(code, company_id)',
        'Practitioner Code must be unique per company.',
    )

    _staff_company_uniq = models.Constraint(
        'unique(staff_id, company_id)',
        'A staff can only be linked once per company as practitioner.',
    )

    _exp_non_negative = models.Constraint(
        'CHECK (experience_years >= 0)',
        'Experience (Years) must be non-negative.',
    )

    # =====================================================================
    # COMPUTES
    # =====================================================================
    @api.depends("code", "name", "specialty")
    def _compute_display_name(self):
        for rec in self:
            parts = []
            if rec.code and rec.code != "/":
                parts.append(f"[{rec.code}]")
            if rec.name:
                parts.append(rec.name)
            if rec.specialty:
                parts.append(f"• {rec.specialty}")
            rec.display_name = " ".join(parts) if parts else _("Practitioner")

    @api.depends("staff_id")
    def _compute_employee_partner_role(self):
        Staff = self.env["clinic.staff"]
        has_employee = "employee_id" in Staff._fields
        has_partner = "partner_id" in Staff._fields
        has_role = "role" in Staff._fields
        for rec in self:
            rec.employee_id = rec.staff_id.employee_id if has_employee else False
            rec.partner_id = rec.staff_id.partner_id if has_partner else False
            rec.role = rec.staff_id.role if has_role else "other"

    @api.depends("staff_id")
    def _compute_compliance(self):
        """Aggregate compliance from clinic.staff.license (if available)."""
        License = self.env.get("clinic.staff.license")
        today = fields.Date.context_today(self)
        for rec in self:
            latest = False
            compliant = True  # default: lenient when license module not installed
            if License and rec.staff_id:
                # consider active licenses, not expired
                ls = License.search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("state", "in", ["active", "valid", "approved"]),
                ])
                # if license module exists but no active licenses, mark not compliant
                compliant = False
                for l in ls:
                    # guard expiry field names
                    exp = False
                    if "valid_to" in l._fields:
                        exp = l.valid_to
                    elif "expiration_date" in l._fields:
                        exp = l.expiration_date
                    elif "date_to" in l._fields:
                        exp = l.date_to
                    # evaluate compliance per license
                    if not exp or exp >= today:
                        compliant = True
                        if not latest or (exp and latest and exp > latest) or (exp and not latest):
                            latest = exp
                rec.license_valid_until = latest or False
            else:
                rec.license_valid_until = False
            rec.is_license_compliant = bool(compliant)

    @api.depends("active", "is_license_compliant", "staff_id")
    def _compute_readiness(self):
        """Ready if active + license compliant + (optional) presence/availability signal."""
        Presence = self.env.get("clinic.staff.presence")
        Availability = self.env.get("clinic.staff.availability")
        Roster = self.env.get("clinic.staff.roster")
        now = fields.Datetime.now()
        for rec in self:
            ready = bool(rec.active and rec.is_license_compliant)
            nxt = False
            # If presence model exists, check current presence
            if ready and Presence and rec.staff_id:
                pr = Presence.search([("staff_id", "=", rec.staff_id.id)], limit=1, order="check_in desc")
                if pr and "state" in pr._fields:
                    # Treat 'present' / 'on_shift' as available hint
                    state = pr.state or "absent"
                    if state not in ("present", "on_shift", "available"):
                        ready = False
            # Provide a soft "next available" hint from availability/roster
            if Availability and rec.staff_id:
                slot = Availability.search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("end", ">", now),
                ], limit=1, order="start asc")
                nxt = slot.start if slot and "start" in slot._fields else False
            elif Roster and rec.staff_id:
                line = Roster.search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("date_end", ">", now),
                ], limit=1, order="date_start asc")
                if line and "date_start" in line._fields:
                    nxt = line.date_start
            rec.is_ready_for_assignment = ready
            rec.next_available_from = nxt

    def _compute_counts(self):
        Assignment = self.env.get("clinic.staff.assignment")
        Availability = self.env.get("clinic.staff.availability")
        License = self.env.get("clinic.staff.license")
        Roster = self.env.get("clinic.staff.roster")

        for rec in self:
            sid = rec.staff_id.id
            rec.assignment_count = Assignment.search_count([("staff_id", "=", sid)]) if Assignment and sid else 0
            rec.availability_count = Availability.search_count([("staff_id", "=", sid)]) if Availability and sid else 0
            rec.license_count = License.search_count([("staff_id", "=", sid)]) if License and sid else 0
            rec.roster_count = Roster.search_count([("staff_id", "=", sid)]) if Roster and sid else 0

    # =====================================================================
    # CREATE / WRITE
    # =====================================================================
    @api.model_create_multi
    def create(self, vals_list):
        seq = self.env["ir.sequence"]
        for vals in vals_list:
            # Generate code if missing
            if not vals.get("code") or vals.get("code") in ("/",):
                vals["code"] = seq.next_by_code("clinic.practitioner") or "/"
            # Default name from staff if not provided
            if not vals.get("name") and vals.get("staff_id"):
                staff = self.env["clinic.staff"].browse(vals["staff_id"])
                vals["name"] = staff.display_name or staff.name or _("Practitioner")
            # Company & branch defaults
            vals.setdefault("company_id", self.env.company.id)
            if vals.get("staff_id") and "branch_id" not in vals:
                Staff = self.env["clinic.staff"].browse(vals["staff_id"])
                if "branch_id" in Staff._fields and Staff.branch_id:
                    vals["branch_id"] = Staff.branch_id.id
        recs = super().create(vals_list)
        return recs

    def write(self, vals):
        # Keep name synchronized if staff changes and name wasn't manually edited
        if "staff_id" in vals and "name" not in vals:
            new_staff = self.env["clinic.staff"].browse(vals.get("staff_id"))
            vals["name"] = new_staff.display_name or new_staff.name
        return super().write(vals)

    # =====================================================================
    # CONSTRAINTS
    # =====================================================================
    @api.constrains("staff_id", "role")
    def _check_staff_role_practitioner(self):
        """Optional guard: only allow practitioner roles."""
        Staff = self.env["clinic.staff"]
        has_role = "role" in Staff._fields
        for rec in self:
            if not rec.staff_id:
                raise ValidationError(_("A practitioner must be linked to a staff."))
            if has_role:
                role = rec.staff_id.role or rec.role
                if role not in ("doctor", "nurse", "therapist", "other"):
                    raise ValidationError(_("Linked staff role is not allowed as practitioner."))

    # =====================================================================
    # NAME GET / SEARCH
    # =====================================================================
    def name_get(self):
        res = []
        for rec in self:
            name = rec.display_name or rec.name or rec.code or _("Practitioner")
            res.append((rec.id, name))
        return res

    @api.model
    def name_search(self, name="", domain=None, operator="ilike", limit=100):
        domain = domain or []
        name_domain = ["|", ("code", operator, name), ("name", operator, name)]
        recs = self.search(name_domain + domain, limit=limit)
        return [(rec.id, rec.display_name) for rec in recs.sudo()]

    # =====================================================================
    # BUSINESS HELPERS
    # =====================================================================
    def action_open_staff(self):
        """Open the linked staff form."""
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Staff"),
            "res_model": "clinic.staff",
            "view_mode": "form",
            "target": "current",
            "res_id": self.staff_id.id,
        }

    def action_view_assignments(self):
        """Open assignments for this practitioner (staff)."""
        self.ensure_one()
        model = "clinic.staff.assignment"
        if not self.env.get(model):
            return False
        return {
            "type": "ir.actions.act_window",
            "name": _("Assignments"),
            "res_model": model,
            "view_mode": "list,form,calendar,gantt",
            "domain": [("staff_id", "=", self.staff_id.id)],
            "target": "current",
        }

    def action_view_availability(self):
        """Open availability slots for this practitioner (staff)."""
        self.ensure_one()
        model = "clinic.staff.availability"
        if not self.env.get(model):
            return False
        return {
            "type": "ir.actions.act_window",
            "name": _("Availability"),
            "res_model": model,
            "view_mode": "calendar,list,form",
            "domain": [("staff_id", "=", self.staff_id.id)],
            "target": "current",
        }

    def action_view_licenses(self):
        """Open licenses for this practitioner (staff)."""
        self.ensure_one()
        model = "clinic.staff.license"
        if not self.env.get(model):
            return False
        return {
            "type": "ir.actions.act_window",
            "name": _("Licenses"),
            "res_model": model,
            "view_mode": "list,form",
            "domain": [("staff_id", "=", self.staff_id.id)],
            "target": "current",
        }

    def action_view_roster(self):
        """Open roster lines for this practitioner (staff)."""
        self.ensure_one()
        model = "clinic.staff.roster"
        if not self.env.get(model):
            return False
        return {
            "type": "ir.actions.act_window",
            "name": _("Roster"),
            "res_model": model,
            "view_mode": "gantt,list,form,calendar",
            "domain": [("staff_id", "=", self.staff_id.id)],
            "target": "current",
        }

    def ensure_license_compliant(self, at_date=None):
        """Raise if license not compliant at given date (default today)."""
        at = at_date or fields.Date.context_today(self)
        for rec in self:
            # If license module absent, allow by design (soft integration).
            if self.env.get("clinic.staff.license"):
                if not rec.is_license_compliant:
                    raise ValidationError(_("Practitioner is not license-compliant."))
                if rec.license_valid_until and rec.license_valid_until < at:
                    raise ValidationError(_("Practitioner's license is expired."))

    def is_available_at(self, at_dt=None):
        """Soft check: available if marked ready and (optionally) coverage exists in availability/roster."""
        at = at_dt or fields.Datetime.now()
        for rec in self:
            if not rec.is_ready_for_assignment:
                return False
            Availability = self.env.get("clinic.staff.availability")
            Roster = self.env.get("clinic.staff.roster")
            if Availability:
                ok = Availability.search_count([
                    ("staff_id", "=", rec.staff_id.id),
                    ("start", "<=", at),
                    ("end", ">=", at),
                ]) > 0
                if ok:
                    return True
            if Roster:
                ok = Roster.search_count([
                    ("staff_id", "=", rec.staff_id.id),
                    ("date_start", "<=", at),
                    ("date_end", ">=", at),
                ]) > 0
                if ok:
                    return True
            # If no availability/roster modules, fall back to readiness
            return True

    # pindah ke addon clinic_care_plan
    # =====================================================================
    # DELETE GUARDS (avoid orphan references)
    # =====================================================================
    # def unlink(self):
    #     CarePlan = self.env.get("clinic.care.plan")
    #     for rec in self:
    #         if CarePlan:
    #             # Name of the M2M field on care plan could be 'practitioner_ids' (spelled properly),
    #             # namun jika di sisi care_plan tertulis 'practioner_ids' pastikan disesuaikan di sana.
    #             # Di sini kita cek keduanya untuk aman.
    #             dom_ok = ["|", ("practitioner_ids", "in", rec.id), ("practioner_ids", "in", rec.id)]
    #             linked = CarePlan.search_count(dom_ok) > 0
    #             if linked:
    #                 raise ValidationError(
    #                     _("Cannot delete practitioner '%s' because it is referenced by one or more Care Plans.")
    #                     % (rec.display_name or rec.name)
    #                 )
    #     return super().unlink()

