
# -*- coding: utf-8 -*-
# ClinicOne - Clinical Staff (Nurse & Therapist) Management
# File: staff_license.py
#
# Catatan (ID):
# - Mencakup dua model:
#   1) clinic.license.type      -> master tipe lisensi (aturan masa berlaku, notice, applicability)
#   2) clinic.staff.license     -> lisensi per staff (lifecycle: draft/active/expiring/suspended/archived)
# - Terintegrasi dengan clinic.staff (relasi), dan siap dipakai lintas modul (encounter/procedure/eMAR/queue).
# - Semua label/help dalam Bahasa Inggris; komentar penjelas menggunakan Bahasa Indonesia.

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError
from datetime import timedelta
import logging

_logger = logging.getLogger(__name__)


# ============================================================
# Master License Type
# ============================================================
class ClinicLicenseType(models.Model):
    _name = "clinic.license.type"
    _description = "Clinic License Type"
    _rec_name = "name"
    _order = "sequence, name"

    # Urutan tampilan
    sequence = fields.Integer(
        string="Sequence",
        default=10,
        help="Defines the order of license types in lists and selections.",
    )

    # Identitas tipe lisensi
    name = fields.Char(
        string="License Type",
        required=True,
        index=True,
        translate=True,
        help="Human-readable name of the license type, e.g., 'Nurse Registration', 'Therapist Certification'.",
    )

    code = fields.Char(
        string="Code",
        required=True,
        copy=False,
        default="/",
        index=True,
        help="Unique license type code generated by sequence.",
    )

    description = fields.Text(
        string="Description",
        translate=True,
        help="Long description, coverage, or regulatory notes.",
    )

    # Applicability per role
    applicable_to_nurse = fields.Boolean(
        string="Applicable to Nurse", default=True,
        help="Mark if this license applies to Nurse role.",
    )
    applicable_to_therapist = fields.Boolean(
        string="Applicable to Therapist", default=True,
        help="Mark if this license applies to Therapist role.",
    )
    applicable_to_doctor = fields.Boolean(
        string="Applicable to Doctor", default=False,
        help="Mark if this license applies to Doctor role.",
    )

    # Aturan masa berlaku & notifikasi
    validity_months = fields.Integer(
        string="Validity (Months)",
        default=0,
        help="Default validity period in months used to auto-compute Expiry Date from Issue Date. "
             "Set 0 if there is no default validity.",
    )

    renewal_notice_days = fields.Integer(
        string="Renewal Notice (Days)",
        default=30,
        help="Number of days before expiry when the license should be considered 'Expiring' "
             "and renewal reminders are triggered.",
    )

    requires_number = fields.Boolean(
        string="Requires License Number",
        default=True,
        help="If enabled, the license number becomes mandatory on staff licenses.",
    )
    requires_issuer = fields.Boolean(
        string="Requires Issuer",
        default=False,
        help="If enabled, issuer fields become mandatory on staff licenses.",
    )
    requires_country = fields.Boolean(
        string="Requires Country/Region",
        default=False,
        help="If enabled, country/state must be specified on staff licenses.",
    )
    requires_attachment = fields.Boolean(
        string="Requires Attachment",
        default=False,
        help="If enabled, at least one supporting document attachment is required.",
    )

    # Multi-company support
    company_id = fields.Many2one(
        "res.company",
        string="Company",
        default=lambda self: self.env.company,
        help="Company for which this license type applies.",
    )

    is_active = fields.Boolean(
        string="Active",
        default=True,
        help="If unchecked, this license type will be hidden from selection.",
    )

    # Back references
    staff_license_ids = fields.One2many(
        "clinic.staff.license",
        "license_type_id",
        string="Staff Licenses",
        help="Staff license records that use this license type.",
    )

    _license_type_code_unique = models.Constraint(
        'unique(code)',
        'License Type Code must be unique.',
    )

    _license_type_name_company_unique = models.Constraint(
        'unique(name, company_id)',
        'License Type name must be unique per company.',
    )

    @api.model_create_multi
    def create(self, vals_list):
        """Generate sequence untuk code jika '/'. """
        for vals in vals_list:
            if not vals.get("code") or vals.get("code") in ("/",):
                vals["code"] = self.env["ir.sequence"].next_by_code("clinic.license.type") or "/"
        return super().create(vals_list)


# ============================================================
# Staff License
# ============================================================
class ClinicStaffLicense(models.Model):
    _name = "clinic.staff.license"
    _description = "Staff License"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _rec_name = "display_name"
    _order = "state desc, expiry_date asc, id desc"

    # Relasi utama
    staff_id = fields.Many2one(
        "clinic.staff",
        string="Staff",
        required=True,
        index=True,
        ondelete="cascade",
        tracking=True,
        help="Staff member who holds this license.",
    )

    license_type_id = fields.Many2one(
        "clinic.license.type",
        string="License Type",
        required=True,
        index=True,
        ondelete="restrict",
        tracking=True,
        help="Type/category of the professional license.",
    )

    # Identitas lisensi
    reference = fields.Char(
        string="License Reference",
        copy=False,
        default="/",
        index=True,
        help="Internal reference generated by sequence for this license record.",
        tracking=True,
    )

    number = fields.Char(
        string="License Number",
        index=True,
        help="The official license or registration number issued by the authority.",
        tracking=True,
    )

    issuer = fields.Char(
        string="Issuer (Name)",
        help="Issuing authority or institution name (plain text).",
        tracking=True,
    )

    issuer_partner_id = fields.Many2one(
        "res.partner",
        string="Issuer (Partner)",
        help="Issuing authority or institution as a partner record.",
        tracking=True,
    )

    country_id = fields.Many2one(
        "res.country",
        string="Country",
        help="Country in which the license is valid or issued.",
        tracking=True,
    )

    state_id = fields.Many2one(
        "res.country.state",
        string="State/Province",
        domain="[('country_id', '=', country_id)]",
        help="State/Province for the license jurisdiction.",
        tracking=True,
    )

    city = fields.Char(
        string="City",
        help="City related to the license jurisdiction.",
    )

    # Masa berlaku
    issue_date = fields.Date(
        string="Issue Date",
        tracking=True,
        help="Date when the license was issued.",
    )

    expiry_date = fields.Date(
        string="Expiry Date",
        index=True,
        tracking=True,
        help="Date when the license expires.",
    )

    days_to_expiry = fields.Integer(
        string="Days to Expiry",
        compute="_compute_dates_flags",
        help="Number of days from today to the expiry date. Negative if already expired.",
        store=False,
    )

    is_expiring_window = fields.Boolean(
        string="Within Expiring Window",
        compute="_compute_dates_flags",
        help="True if the license is within the renewal notice window.",
        store=False,
    )

    # Status lifecycle
    state = fields.Selection(
        selection=[
            ("draft", "Draft"),
            ("active", "Active"),
            ("expiring", "Expiring"),
            ("suspended", "Suspended"),
            ("archived", "Archived"),
            ("expired", "Expired"),
        ],
        string="Status",
        default="draft",
        index=True,
        tracking=True,
        help="Lifecycle status: Draft/Active/Expiring/Suspended/Archived/Expired.",
    )

    active = fields.Boolean(
        string="Active (Record)",
        default=True,
        help="Technical active flag to hide archived records from views.",
    )

    # Verifikasi & bukti
    verification_url = fields.Char(
        string="Verification URL",
        help="Public/portal URL of the authority where this license can be verified.",
    )

    verified = fields.Boolean(
        string="Verified",
        default=False,
        help="Check if this license has been verified against the issuer or authority.",
        tracking=True,
    )

    verified_on = fields.Datetime(
        string="Verified On",
        help="Timestamp when the license was verified.",
        tracking=True,
    )

    verified_by = fields.Many2one(
        "res.users",
        string="Verified By",
        help="User who verified the license details.",
        tracking=True,
    )

    attachment_ids = fields.Many2many(
        "ir.attachment",
        relation="clinic_staff_license_ir_attachment_rel",
        column1="license_id",
        column2="attachment_id",
        string="Attachments",
        help="Supporting documents such as scanned certificates or letters.",
    )

    attachment_count = fields.Integer(
        string="Attachment Count",
        compute="_compute_attachment_count",
        store=False,
        help="Number of attachments linked to this license.",
    )

    notes = fields.Text(
        string="Notes",
        help="Additional remarks regarding exceptions, constraints, or renewal progress.",
    )

    # Multi-company & branch
    company_id = fields.Many2one(
        "res.company",
        string="Company",
        related="staff_id.company_id",
        store=True,
        readonly=True,
        help="Company of the staff member.",
    )

    # branch_id = fields.Many2one(
    #     "clinic.branch",
    #     string="Branch",
    #     help="Operational branch context for this license, if applicable.",
    # )

    # Tampilan gabungan
    display_name = fields.Char(
        string="Display Name",
        compute="_compute_display_name",
        store=True,
        help="Composite label: [Ref] Staff - License Type (Number).",
    )

    _license_number_unique_per_company = models.Constraint(
        'unique(license_type_id, number, company_id)',
        'License Number must be unique per license type and company.',
    )

    # =========================
    # Compute helpers
    # =========================
    @api.depends("reference", "staff_id.display_name", "license_type_id.name", "number")
    def _compute_display_name(self):
        """Bangun label tampilan gabungan."""
        for rec in self:
            parts = []
            if rec.reference and rec.reference not in ("/",):
                parts.append(f"[{rec.reference}]")
            if rec.staff_id:
                parts.append(rec.staff_id.display_name or _("(No Staff)"))
            if rec.license_type_id:
                parts.append(f"- {rec.license_type_id.name}")
            if rec.number:
                parts.append(f"({rec.number})")
            rec.display_name = " ".join(parts) if parts else _("Staff License")

    def _today(self):
        """Abstraksi tanggal hari ini agar mudah di-mock di unit test."""
        return fields.Date.context_today(self)

    @api.depends("expiry_date", "license_type_id.renewal_notice_days")
    def _compute_dates_flags(self):
        """Hitung sisa hari ke expiry dan flag expiring window."""
        today = self._today()
        for rec in self:
            rec.days_to_expiry = 0
            rec.is_expiring_window = False
            if rec.expiry_date:
                delta = rec.expiry_date - today
                rec.days_to_expiry = delta.days
                window = rec.license_type_id.renewal_notice_days or 0
                rec.is_expiring_window = (0 <= delta.days <= window)

    def _compute_attachment_count(self):
        for rec in self:
            rec.attachment_count = len(rec.attachment_ids)

    # =========================
    # Onchange & Defaults
    # =========================
    @api.onchange("issue_date", "license_type_id")
    def _onchange_dates_by_type(self):
        """Auto hitung expiry dari issue + validity_months jika expiry belum diisi."""
        for rec in self:
            if rec.issue_date and rec.license_type_id and not rec.expiry_date:
                months = rec.license_type_id.validity_months or 0
                if months > 0:
                    # Gunakan utilitas add_months sederhana (approx via relativedelta jika tersedia)
                    try:
                        from dateutil.relativedelta import relativedelta
                        rec.expiry_date = rec.issue_date + relativedelta(months=+months)
                    except Exception:
                        # Fallback kasar: 30 hari x months
                        rec.expiry_date = rec.issue_date + timedelta(days=30 * months)

    # =========================
    # Lifecycle helpers
    # =========================
    def _recompute_state_by_dates(self):
        """Evaluasi status berdasarkan tanggal kadaluarsa dan window expiring."""
        today = self._today()
        for rec in self:
            if rec.state in ("archived", "suspended"):
                # Jangan override status manual yang bersifat final/transient
                continue
            if rec.expiry_date:
                if rec.expiry_date < today:
                    new_state = "expired"
                else:
                    # Aktif atau masuk window expiring
                    if rec.is_expiring_window:
                        new_state = "expiring"
                    else:
                        new_state = "active"
            else:
                # Tanpa expiry, jika sudah issue_date maka active, selainnya draft
                new_state = "active" if rec.issue_date else "draft"

            if rec.state != new_state:
                rec.state = new_state

    def _maybe_schedule_expiry_activity(self):
        """Jadwalkan activity untuk pengingat perpanjangan jika masuk window expiring."""
        for rec in self:
            if not rec.expiry_date:
                continue
            if rec.state not in ("active", "expiring"):
                continue
            try:
                notice_days = rec.license_type_id.renewal_notice_days or 0
                if notice_days <= 0:
                    continue
                deadline = rec.expiry_date - timedelta(days=notice_days)
                if deadline and deadline >= self._today():
                    rec.activity_schedule(
                        "mail.mail_activity_data_todo",
                        date_deadline=deadline,
                        summary=_("Renew license before expiry"),
                        note=_(
                            "License '%(name)s' will expire on %(date)s. "
                            "Please start the renewal process."
                        ) % {"name": rec.display_name, "date": rec.expiry_date},
                    )
            except Exception as e:
                _logger.warning("Failed to schedule renewal activity for %s: %s", rec.display_name, e)

    # =========================
    # CRUD overrides
    # =========================
    @api.model_create_multi
    def create(self, vals_list):
        """Set reference dari sequence, validasi isian wajib sesuai tipe, dan evaluasi status."""
        records = self.browse()
        for vals in vals_list:
            if not vals.get("reference") or vals.get("reference") in ("/",):
                vals["reference"] = self.env["ir.sequence"].next_by_code("clinic.staff.license") or "/"
        records = super().create(vals_list)

        # Validasi isian wajib (berdasarkan tipe)
        for rec in records:
            rec._validate_required_by_type()
            rec._recompute_state_by_dates()
            rec._maybe_schedule_expiry_activity()

            # Jika tipe mengharuskan attachment dan belum ada -> buat activity
            if rec.license_type_id.requires_attachment and not rec.attachment_ids:
                rec.activity_schedule(
                    "mail.mail_activity_data_todo",
                    summary=_("Attach supporting documents"),
                    note=_("This license type requires at least one supporting attachment."),
                )
        return records

    def write(self, vals):
        """Re-evaluasi status dan aktivitas pengingat saat tanggal/tipe berubah."""
        res = super().write(vals)

        # Validasi isian wajib jika fields kunci berubah
        keys = {"license_type_id", "number", "issuer", "issuer_partner_id", "country_id", "state_id"}
        if keys.intersection(vals.keys()):
            for rec in self:
                rec._validate_required_by_type()

        # Evaluasi status & activity bila tanggal berubah
        if {"issue_date", "expiry_date", "license_type_id"}.intersection(vals.keys()):
            for rec in self:
                rec._recompute_state_by_dates()
                rec._maybe_schedule_expiry_activity()
        return res

    # =========================
    # Business validations
    # =========================
    def _validate_required_by_type(self):
        """Validasi kewajiban field berdasarkan aturan pada License Type."""
        for rec in self:
            lt = rec.license_type_id
            if not lt:
                continue
            # number wajib?
            if lt.requires_number and not rec.number:
                raise ValidationError(_("License Number is required for this License Type."))
            # issuer wajib?
            if lt.requires_issuer and not (rec.issuer or rec.issuer_partner_id):
                raise ValidationError(_("Issuer is required for this License Type (name or partner)."))
            # negara/wilayah wajib?
            if lt.requires_country and not rec.country_id:
                raise ValidationError(_("Country is required for this License Type."))
            # attachment wajib? (diperiksa di create; disini validasi juga saat write)
            if lt.requires_attachment and not rec.attachment_ids:
                # Tidak raise langsung agar tidak menghambat update; gunakan activity.
                self.activity_schedule(
                    "mail.mail_activity_data_todo",
                    summary=_("Attach supporting documents"),
                    note=_("This license type requires at least one supporting attachment."),
                )

    @api.constrains("issue_date", "expiry_date")
    def _check_dates(self):
        for rec in self:
            if rec.issue_date and rec.expiry_date and rec.expiry_date < rec.issue_date:
                raise ValidationError(_("Expiry Date cannot be earlier than Issue Date."))

    # =========================
    # Actions (UI / Wizards)
    # =========================
    def action_mark_verified(self):
        """Tandai lisensi sebagai terverifikasi."""
        for rec in self:
            rec.write({
                "verified": True,
                "verified_on": fields.Datetime.now(),
                "verified_by": self.env.user.id,
            })
        return True

    def action_set_draft(self):
        """Kembalikan status ke Draft (kecuali archived)."""
        for rec in self:
            if rec.state == "archived":
                raise ValidationError(_("Cannot revert from Archived to Draft."))
            rec.state = "draft"
        return True

    def action_activate(self):
        """Set status Active (atau Expiring jika sudah masuk window)."""
        for rec in self:
            if rec.state == "archived":
                raise ValidationError(_("Cannot activate an Archived license."))
            rec._recompute_state_by_dates()
            if rec.state in ("draft", "expired", "suspended"):
                # Paksa ke active jika memenuhi syarat tanggal
                if rec.expiry_date:
                    today = rec._today()
                    if rec.expiry_date < today:
                        raise ValidationError(_("Cannot activate an expired license. Please renew."))
                    rec.state = "expiring" if rec.is_expiring_window else "active"
                else:
                    rec.state = "active"
            rec._maybe_schedule_expiry_activity()
        return True

    def action_suspend(self):
        """Tangguhkan lisensi (mis. pelanggaran/komplain)."""
        for rec in self:
            if rec.state == "archived":
                raise ValidationError(_("Cannot suspend an Archived license."))
            rec.state = "suspended"
        return True

    def action_archive(self):
        """Arsipkan lisensi (menonaktifkan secara final)."""
        for rec in self:
            rec.state = "archived"
            rec.active = False
        return True

    def action_open_attachments(self):
        """Buka lampiran bukti lisensi."""
        self.ensure_one()
        return {
            "name": _("Attachments"),
            "type": "ir.actions.act_window",
            "res_model": "ir.attachment",
            "view_mode": "kanban,list,form",
            "domain": [("id", "in", self.attachment_ids.ids)],
            "context": {"default_res_model": self._name, "default_res_id": self.id},
        }

    def action_open_renewal_wizard(self):
        """Buka wizard renewal (jika modul wizard tersedia), fallback ke form jika tidak ada."""
        self.ensure_one()
        Wizard = self.env.get("clinic.staff.license.renewal.wizard")
        if Wizard:
            # Buka wizard standar
            return {
                "name": _("Renew License"),
                "type": "ir.actions.act_window",
                "res_model": "clinic.staff.license.renewal.wizard",
                "view_mode": "form",
                "target": "new",
                "context": {"default_license_id": self.id},
            }
        # Fallback: buka record form untuk perpanjangan manual
        return {
            "name": _("License"),
            "type": "ir.actions.act_window",
            "res_model": "clinic.staff.license",
            "view_mode": "form",
            "res_id": self.id,
            "target": "current",
        }

    # =========================
    # Integration helpers
    # =========================
    def is_currently_valid(self):
        """True jika status 'active'/'expiring' dan belum melewati expiry_date."""
        today = self._today()
        for rec in self:
            if rec.state in ("active", "expiring"):
                if rec.expiry_date and rec.expiry_date < today:
                    return False
                return True
        return False

    def contributes_to_staff_eligibility(self):
        """Dipakai modul lain untuk cek eligibility klinis (soft contract)."""
        # Lisensi dinilai berkontribusi jika state active/expiring (belum kadaluarsa).
        return any(self.filtered(lambda l: l.is_currently_valid()))

    # =========================
    # Name get
    # =========================
    def name_get(self):
        res = []
        for rec in self:
            name = rec.display_name or rec.reference or _("Staff License")
            res.append((rec.id, name))
        return res
