

# -*- coding: utf-8 -*-
# ClinicOne - Clinical Staff (Nurse & Therapist) Management
# File: staff_roster.py
#
# Catatan (ID):
# - Terintegrasi holistik dengan:
#   * clinic.staff (model inti staff)
#   * clinic.staff.availability(.occurrence) untuk pengecekan ketersediaan / blocking
#   * clinic.staff.assignment (akan dibuat di file terpisah) untuk penugasan operasional
#   * Modul lintas (room/queue/procedure/encounter/telemed) via fields.Reference + env.get
# - Semua label/help dalam Bahasa Inggris; komentar penjelas menggunakan Bahasa Indonesia.

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError
from datetime import datetime, timedelta
import logging

_logger = logging.getLogger(__name__)


# ============================================================
# Shift Template (Master)
# ============================================================
class ClinicShiftTemplate(models.Model):
    _name = "clinic.shift.template"
    _description = "Shift Template"
    _rec_name = "name"
    _order = "sequence, name"

    sequence = fields.Integer(
        string="Sequence",
        default=10,
        help="Ordering of shift templates in lists and pickers.",
    )

    name = fields.Char(
        string="Template Name",
        required=True,
        translate=True,
        help="Human-readable name, e.g., 'Morning', 'Afternoon', 'Night', 'Weekend'.",
    )

    code = fields.Char(
        string="Code",
        required=True,
        copy=False,
        default="/",
        index=True,
        help="Unique code generated by sequence for shift template.",
    )

    # Jam mulai & durasi (jam) — dipakai untuk membentuk start/stop roster harian
    start_time = fields.Float(
        string="Start Time (Hours)",
        required=True,
        help="Hour-of-day in 24h format (e.g., 8.0 = 08:00, 13.5 = 13:30).",
    )
    duration_hours = fields.Float(
        string="Duration (Hours)",
        required=True,
        help="Duration of the shift in hours (e.g., 8.0).",
    )

    # Hari aktif: template dapat dibatasi ke hari tertentu (untuk generator)
    active_mon = fields.Boolean("Mon", default=True)
    active_tue = fields.Boolean("Tue", default=True)
    active_wed = fields.Boolean("Wed", default=True)
    active_thu = fields.Boolean("Thu", default=True)
    active_fri = fields.Boolean("Fri", default=True)
    active_sat = fields.Boolean("Sat", default=False)
    active_sun = fields.Boolean("Sun", default=False)

    role_applicability = fields.Selection(
        selection=[
            ("any", "Any"),
            ("nurse", "Nurse"),
            ("therapist", "Therapist"),
            ("doctor", "Doctor"),
        ],
        string="Role Applicability",
        default="any",
        help="If set, the shift is intended for a specific role.",
    )

    # default_branch_id = fields.Many2one(
    #     "clinic.branch",
    #     string="Default Branch",
    #     help="Default branch where this shift template is typically used.",
    # )

    color = fields.Integer(
        string="Color",
        help="Optional color index for calendar views.",
    )

    company_id = fields.Many2one(
        "res.company",
        string="Company",
        default=lambda self: self.env.company,
        help="Company context for the shift template.",
    )

    is_active = fields.Boolean(
        string="Active",
        default=True,
        help="If unchecked, this template will be hidden from selection.",
    )

    _shift_template_code_unique = models.Constraint(
        'unique(code)',
        'Shift Template Code must be unique.',
    )

    _shift_template_name_company_unique = models.Constraint(
        'unique(name, company_id)',
        'Shift Template name must be unique per company.',
    )

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get("code") or vals.get("code") in ("/",):
                vals["code"] = self.env["ir.sequence"].next_by_code("clinic.shift.template") or "/"
        return super().create(vals_list)

    # Utility: apakah hari aktif?
    def _is_active_weekday(self, dt: datetime) -> bool:
        self.ensure_one()
        idx = dt.weekday()  # 0=Mon..6=Sun
        return [
            self.active_mon, self.active_tue, self.active_wed, self.active_thu,
            self.active_fri, self.active_sat, self.active_sun
        ][idx]


# ============================================================
# Staff Roster (Per-Shift Entry)
# ============================================================
class ClinicStaffRoster(models.Model):
    _name = "clinic.staff.roster"
    _description = "Staff Roster"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _rec_name = "display_name"
    _order = "start, staff_id, id"

    # -------------------------
    # Relasi & Identitas
    # -------------------------
    name = fields.Char(
        string="Title",
        help="Optional free-text title for this roster entry.",
        translate=True,
    )

    staff_id = fields.Many2one(
        "clinic.staff",
        string="Staff",
        required=True,
        index=True,
        ondelete="cascade",
        tracking=True,
        help="Staff scheduled for this roster entry.",
    )

    template_id = fields.Many2one(
        "clinic.shift.template",
        string="Shift Template",
        help="If this roster was created from a shift template.",
        tracking=True,
    )

    company_id = fields.Many2one(
        "res.company",
        string="Company",
        related="staff_id.company_id",
        store=True,
        readonly=True,
        help="Company of the staff member.",
    )

    branch_id = fields.Many2one(
        "clinic.branch",
        string="Branch",
        help="Operational branch for this roster entry.",
        tracking=True,
    )

    role = fields.Selection(
        selection=[
            ("nurse", "Nurse"),
            ("therapist", "Therapist"),
            ("doctor", "Doctor"),
            ("other", "Other"),
        ],
        string="Role",
        help="Role context for this shift (may affect routing and KPIs).",
        tracking=True,
    )

    # -------------------------
    # Waktu & Durasi
    # -------------------------
    start = fields.Datetime(
        string="Start",
        required=True,
        index=True,
        tracking=True,
        help="Start datetime of the shift (UTC).",
    )

    stop = fields.Datetime(
        string="Stop",
        required=True,
        index=True,
        tracking=True,
        help="End datetime of the shift (UTC).",
    )

    duration_hours = fields.Float(
        string="Duration (Hours)",
        compute="_compute_duration_hours",
        store=False,
        help="Total duration of this roster entry in hours.",
    )

    # -------------------------
    # Keterkaitan Operasional
    # -------------------------
    availability_occurrence_id = fields.Many2one(
        "clinic.staff.availability.occurrence",
        string="Availability Occurrence",
        help="Linked availability occurrence that this roster is based on.",
        ondelete="set null",
    )

    assignment_ids = fields.One2many(
        "clinic.staff.assignment",  # akan ada di file staff_assignment.py
        "roster_id",
        string="Assignments",
        help="Operational assignments (room/queue/procedure) scheduled during this shift.",
    )

    # Referensi fleksibel ke entitas lintas modul (room/queue/procedure/encounter/telemed)
    # location_ref = fields.Reference(
    #     selection=lambda self: self._ref_location_models(),
    #     string="Location Reference",
    #     help="Generic reference to Room/Queue/Stage/etc. Use this to link shift location flexibly.",
    # )

    # procedure_ref = fields.Reference(
    #     selection=lambda self: self._ref_procedure_models(),
    #     string="Procedure Reference",
    #     help="Optional reference to a Procedure or Treatment Session related to the shift.",
    # )

    # -------------------------
    # Status & Kontrol
    # -------------------------
    state = fields.Selection(
        selection=[
            ("draft", "Draft"),
            ("published", "Published"),
            ("in_progress", "In Progress"),
            ("completed", "Completed"),
            ("cancelled", "Cancelled"),
        ],
        string="Status",
        default="draft",
        index=True,
        tracking=True,
        help="Lifecycle state of the roster entry.",
    )

    published_by = fields.Many2one(
        "res.users",
        string="Published By",
        help="User who published the roster.",
        tracking=True,
    )

    published_on = fields.Datetime(
        string="Published On",
        help="Timestamp when the roster was published.",
        tracking=True,
    )

    # Konflik cepat
    # conflict_availability = fields.Boolean(
    #     string="Availability Conflict",
    #     compute="_compute_conflicts",
    #     store=False,
    #     help="True if overlapping with a blocking availability window.",
    # )
    # conflict_other_roster = fields.Boolean(
    #     string="Roster Overlap",
    #     compute="_compute_conflicts",
    #     store=False,
    #     help="True if overlapping with another roster for the same staff.",
    # )
    # conflict_assignment = fields.Boolean(
    #     string="Assignment Overlap",
    #     compute="_compute_conflicts",
    #     store=False,
    #     help="True if overlapping with active assignments (when blocking).",
    # )

    color = fields.Integer(
        string="Color",
        help="Optional color index for calendar views.",
    )

    display_name = fields.Char(
        string="Display Name",
        compute="_compute_display_name",
        store=True,
        help="Composite label for this roster entry.",
    )

    notes = fields.Text(
        string="Notes",
        help="Additional remarks or instructions for the shift.",
    )

    active = fields.Boolean(
        string="Active",
        default=True,
        help="If unchecked, this roster entry will be hidden from most views.",
    )

    _check_start_before_stop = models.Constraint(
        'CHECK (start < stop)',
        'The Start must be earlier than the Stop.',
    )

    # -------------------------------------------------------
    # Reference model selection (flexible cross-module link)
    # -------------------------------------------------------
    # def _ref_location_models(self):
    #     """Daftar model referensi yang umum dipakai untuk 'lokasi' shift.
    #     Aman meskipun beberapa model belum terpasang; fields.Reference hanya
    #     menyimpan string model dan ID jika ada record.
    #     """
    #     return [
    #         ("clinic.room", "Clinic Room"),
    #         ("clinic.room.assignment", "Room Assignment"),
    #         ("clinic.queue", "Clinic Queue"),
    #         ("clinic.queue.stage", "Queue Stage"),
    #         ("clinic.queue.token", "Queue Token"),
    #         ("clinic.encounter", "Clinical Encounter"),
    #     ]

    # def _ref_procedure_models(self):
    #     """Daftar model referensi untuk prosedur/treatment yang relevan dengan shift."""
    #     return [
    #         ("clinic.procedure", "Clinical Procedure"),
    #         ("clinic.procedure.session", "Treatment Session"),
    #     ]

    # -------------------------
    # Compute
    # -------------------------
    def _compute_duration_hours(self):
        for rec in self:
            rec.duration_hours = 0.0
            if rec.start and rec.stop:
                delta = rec.stop - rec.start
                rec.duration_hours = (delta.total_seconds() / 3600.0)

    @api.depends("staff_id.display_name", "start", "stop", "state", "template_id.name")
    def _compute_display_name(self):
        for rec in self:
            parts = []
            if rec.staff_id:
                parts.append(rec.staff_id.display_name or _("(No Staff)"))
            if rec.template_id:
                parts.append(f"- {rec.template_id.name}")
            if rec.state:
                parts.append(f"[{dict(self._fields['state'].selection).get(rec.state)}]")
            if rec.start and rec.stop:
                parts.append(f"({fields.Datetime.to_string(rec.start)} → {fields.Datetime.to_string(rec.stop)})")
            rec.display_name = " ".join(parts) if parts else _("Staff Roster")

    def _overlap_domain(self, start_dt, end_dt):
        return [("start", "<", end_dt), ("stop", ">", start_dt)]

    # def _compute_conflicts(self):
    #     Av = self.env.get("clinic.staff.availability")
    #     AvOcc = self.env.get("clinic.staff.availability.occurrence")
    #     Assign = self.env.get("clinic.staff.assignment")
    #     for rec in self:
    #         rec.conflict_availability = False
    #         rec.conflict_other_roster = False
    #         rec.conflict_assignment = False

    #         if rec.staff_id and rec.start and rec.stop:
    #             # Konflik dengan roster lain (overlap pada staff yang sama)
    #             dom_roster = [
    #                 ("id", "!=", rec.id),
    #                 ("staff_id", "=", rec.staff_id.id),
    #             ] + self._overlap_domain(rec.start, rec.stop)
    #             try:
    #                 rec.conflict_other_roster = bool(self.search_count(dom_roster))
    #             except Exception:
    #                 _logger.debug("Roster overlap check failed (%s)", rec.id)

    #             # Konflik dengan availability blocking
    #             try:
    #                 conflict = False
    #                 if Av:
    #                     dom_av = [
    #                         ("staff_id", "=", rec.staff_id.id),
    #                         ("is_blocking", "=", True),
    #                     ] + [
    #                         ("start", "<", rec.stop),
    #                         ("stop", ">", rec.start),
    #                     ]
    #                     conflict = conflict or bool(Av.sudo().search_count(dom_av))
    #                 if AvOcc:
    #                     dom_oc = [
    #                         ("staff_id", "=", rec.staff_id.id),
    #                         ("is_blocking", "=", True),
    #                         ("state", "in", ("planned", "applied")),
    #                     ] + [
    #                         ("start", "<", rec.stop),
    #                         ("stop", ">", rec.start),
    #                     ]
    #                     conflict = conflict or bool(AvOcc.sudo().search_count(dom_oc))
    #                 rec.conflict_availability = conflict
    #             except Exception:
    #                 _logger.debug("Availability conflict check failed (%s)", rec.id)

    #             # Konflik dengan assignment aktif (bila overlapping)
    #             if Assign:
    #                 try:
    #                     dom_as = [
    #                         ("staff_id", "=", rec.staff_id.id),
    #                         ("state", "in", ("draft", "confirmed", "in_progress")),
    #                     ] + [
    #                         ("start", "<", rec.stop),
    #                         ("stop", ">", rec.start),
    #                     ]
    #                     rec.conflict_assignment = bool(Assign.sudo().search_count(dom_as))
    #                 except Exception:
    #                     _logger.debug("Assignment overlap check failed (%s)", rec.id)

    # -------------------------
    # Constraints
    # -------------------------
    @api.constrains("start", "stop", "staff_id", "state")
    def _check_overlap_basic(self):
        """Cegah dua roster overlap pada staff yang sama saat status aktif (published or beyond)."""
        for rec in self.filtered(lambda r: r.state in ("published", "in_progress")):
            domain = [
                ("id", "!=", rec.id),
                ("staff_id", "=", rec.staff_id.id),
                ("state", "in", ("published", "in_progress")),
            ] + self._overlap_domain(rec.start, rec.stop)
            if self.search_count(domain):
                raise ValidationError(_("This roster overlaps with another active roster for the same staff."))

    # -------------------------
    # Utility
    # -------------------------
    def _staff_is_eligible(self):
        """Gunakan helper dari model staff (can_be_scheduled)."""
        for rec in self:
            if not rec.staff_id.can_be_scheduled:
                raise ValidationError(
                    _("Staff '%s' is not eligible for clinical scheduling.") % (rec.staff_id.display_name,)
                )
        return True

    def _ensure_no_blocking_availability(self):
        """Prevent publishing a roster that overlaps blocking availability."""
        Availability = self.env.get("clinic.staff.availability")
        Occurrence = self.env.get("clinic.staff.availability.occurrence")
        for rec in self:
            conflict = False
            if "conflict_availability" in rec._fields:
                conflict = bool(rec.conflict_availability)
            elif rec.staff_id and rec.start and rec.stop:
                if Availability:
                    conflict = bool(Availability.sudo().search_count([
                        ("staff_id", "=", rec.staff_id.id),
                        ("is_blocking", "=", True),
                        ("active", "=", True),
                        ("start", "<", rec.stop),
                        ("stop", ">", rec.start),
                    ]))
                if not conflict and Occurrence:
                    conflict = bool(Occurrence.sudo().search_count([
                        ("staff_id", "=", rec.staff_id.id),
                        ("is_blocking", "=", True),
                        ("state", "in", ("planned", "applied")),
                        ("start", "<", rec.stop),
                        ("stop", ">", rec.start),
                    ]))
            if conflict:
                raise ValidationError(
                    _("This roster conflicts with blocking availability windows. Please resolve availability first.")
                )
        return True

    # -------------------------
    # Actions / Workflow
    # -------------------------
    def action_publish(self):
        """Terbitkan roster: validasi eligibility & konflik, set published_on/by."""
        for rec in self:
            if rec.state not in ("draft",):
                continue
            rec._staff_is_eligible()
            rec._ensure_no_blocking_availability()

            rec.write({
                "state": "published",
                "published_on": fields.Datetime.now(),
                "published_by": self.env.user.id,
            })
            rec.message_post(body=_("Roster published."))
        return True

    def action_start(self):
        """Mulai shift (In Progress)."""
        now = fields.Datetime.now()
        for rec in self:
            if rec.state not in ("published",):
                continue
            if rec.start and now < rec.start - timedelta(minutes=30):
                # optional: cegah start terlalu dini
                pass
            rec.state = "in_progress"
            rec.message_post(body=_("Roster in progress."))
        return True

    def action_complete(self):
        """Selesaikan shift (Completed)."""
        for rec in self:
            if rec.state not in ("in_progress",):
                continue
            rec.state = "completed"
            rec.message_post(body=_("Roster completed."))
        return True

    def action_cancel(self):
        """Batalkan roster."""
        for rec in self:
            if rec.state in ("completed",):
                raise ValidationError(_("Completed roster cannot be cancelled."))
            rec.state = "cancelled"
            rec.message_post(body=_("Roster cancelled."))
        return True

    def action_reopen(self):
        """Kembalikan ke Draft (jika belum completed)."""
        for rec in self:
            if rec.state == "completed":
                raise ValidationError(_("Completed roster cannot be reopened."))
            rec.state = "draft"
            rec.message_post(body=_("Roster set back to Draft."))
        return True

    # -------------------------
    # Generator from Template
    # -------------------------
    def _float_hour_to_daytime(self, base_date: datetime, hour_float: float) -> datetime:
        """Konversi jam float (8.5 -> 08:30) menjadi datetime pada tanggal tertentu (UTC)."""
        hour = int(hour_float)
        minutes = int(round((hour_float - hour) * 60))
        return base_date.replace(hour=hour, minute=minutes, second=0, microsecond=0)

    @api.model
    def generate_from_template(self, template_id, staff_ids, date_from, date_to, branch_id=False, role=False):
        """Generate roster dari template pada rentang tanggal untuk beberapa staff.
        - Menghormati hari aktif template.
        - Tidak memaksa cek availability; publish dilakukan terpisah.
        - Menghindari duplikasi (cek overlap exact untuk staff pada jam sama).
        Return: jumlah roster dibuat.
        """
        if not template_id or not staff_ids or not date_from or not date_to:
            return 0

        template = self.env["clinic.shift.template"].browse(template_id)
        if not template.exists():
            return 0

        created = 0
        # Iterasi setiap hari dalam rentang
        day = date_from
        while day <= date_to:
            if template._is_active_weekday(day):
                start_dt = self._float_hour_to_daytime(day, template.start_time)
                stop_dt = start_dt + timedelta(hours=template.duration_hours)

                for staff in self.env["clinic.staff"].browse(staff_ids).exists():
                    vals = {
                        "staff_id": staff.id,
                        "template_id": template.id,
                        "branch_id": branch_id or False,
                        "role": role or (staff.role if staff.role in ("nurse", "therapist", "doctor") else "other"),
                        "start": start_dt,
                        "stop": stop_dt,
                        "state": "draft",
                        "color": template.color or 0,
                    }
                    # Cegah duplikasi exact time window untuk staff yang sama
                    exists = self.search_count([
                        ("staff_id", "=", staff.id),
                        ("start", "=", start_dt),
                        ("stop", "=", stop_dt),
                        ("state", "!=", "cancelled"),
                    ])
                    if not exists:
                        self.create(vals)
                        created += 1
            day = day + timedelta(days=1)
        return created

    # -------------------------
    # Name get
    # -------------------------
    def name_get(self):
        res = []
        for rec in self:
            name = rec.display_name or _("Staff Roster")
            res.append((rec.id, name))
        return res

