
# -*- coding: utf-8 -*-
# ClinicOne - Clinical Staff (Nurse & Therapist) Management
# File: staff_assignment.py
#
# Catatan (ID):
# - Model inti: clinic.staff.assignment
# - Fokus: penugasan Staff ke Ruangan/Antrian/Tindakan/Telemedicine.
# - Integrasi:
#     * clinic.staff (wajib)
#     * clinic.staff.roster (opsional tetapi direkomendasikan)
#     * clinic.patient (dipakai untuk konteks pasien)
#     * clinic.skill (requirement) & clinic.staff.skill (compliance)
#     * clinic.incident, clinic.postcare.task, clinic.telemedicine.thread (jika terpasang)
# - Validasi:
#     * rentang waktu (start < stop)
#     * konflik dengan Availability (blocking)
#     * berada di dalam jendela Roster (opsional tetapi direkomendasikan)
#     * larang overlap assignment lain (kecuali allow_overlap=True)
# - Semua label/help dalam Bahasa Inggris; komentar penjelas menggunakan Bahasa Indonesia.

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError
from datetime import timedelta
import logging

_logger = logging.getLogger(__name__)


class ClinicStaffAssignment(models.Model):
    _name = "clinic.staff.assignment"
    _description = "Staff Assignment"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _rec_name = "display_name"
    _order = "state desc, priority desc, start, id"

    # =========================================================
    # Identitas & Relasi
    # =========================================================
    reference = fields.Char(
        string="Reference",
        copy=False,
        default="/",
        index=True,
        help="Internal reference generated by sequence.",
        tracking=True,
    )

    name = fields.Char(
        string="Title",
        translate=True,
        help="Optional title for the assignment.",
        tracking=True,
    )

    staff_id = fields.Many2one(
        "clinic.staff",
        string="Staff",
        required=True,
        index=True,
        ondelete="cascade",
        help="Staff assigned to this task.",
        tracking=True,
    )

    # patient_id = fields.Many2one(
    #     "clinic.patient",
    #     string="Patient",
    #     index=True,
    #     ondelete="set null",
    #     help="Patient context for this assignment, when applicable.",
    #     tracking=True,
    # )

    roster_id = fields.Many2one(
        "clinic.staff.roster",
        string="Roster",
        index=True,
        ondelete="set null",
        help="Roster entry that frames this assignment time window.",
        tracking=True,
    )

    company_id = fields.Many2one(
        "res.company",
        string="Company",
        related="staff_id.company_id",
        store=True,
        readonly=True,
        help="Company of the staff member.",
    )

    # branch_id = fields.Many2one(
    #     "clinic.branch",
    #     string="Branch",
    #     help="Operational branch context for this assignment.",
    #     tracking=True,
    # )

    # =========================================================
    # Klasifikasi Penugasan
    # =========================================================
    assignment_type = fields.Selection(
        selection=[
            ("room", "Room"),
            ("queue", "Queue"),
            ("procedure", "Procedure"),
            ("telemed", "Telemedicine"),
            ("other", "Other"),
        ],
        string="Assignment Type",
        required=True,
        default="room",
        index=True,
        help="Type of the operational assignment.",
        tracking=True,
    )

    # Referensi fleksibel lintas modul
    # location_ref = fields.Reference(
    #     selection=lambda self: self._ref_location_models(),
    #     string="Location Reference",
    #     help="Generic reference to Room/Queue/Encounter context.",
    # )

    # procedure_ref = fields.Reference(
    #     selection=lambda self: self._ref_procedure_models(),
    #     string="Procedure Reference",
    #     help="Reference to a Procedure or Treatment Session related to this assignment.",
    # )

    # telemed_thread_id = fields.Many2one(
    #     "clinic.telemedicine.thread",
    #     string="Telemedicine Thread",
    #     ondelete="set null",
    #     help="Telemedicine thread handled in this assignment.",
    # )

    # =========================================================
    # Waktu (Rencana vs Realisasi) & SLA
    # =========================================================
    start = fields.Datetime(
        string="Planned Start",
        required=True,
        index=True,
        help="Planned start datetime (UTC).",
        tracking=True,
    )

    stop = fields.Datetime(
        string="Planned Stop",
        required=True,
        index=True,
        help="Planned end datetime (UTC).",
        tracking=True,
    )

    actual_start = fields.Datetime(
        string="Actual Start",
        help="Actual start datetime when the work began.",
        tracking=True,
    )

    actual_stop = fields.Datetime(
        string="Actual Stop",
        help="Actual end datetime when the work completed.",
        tracking=True,
    )

    planned_minutes = fields.Integer(
        string="Planned Duration (min)",
        compute="_compute_durations",
        store=False,
        help="Planned duration in minutes.",
    )

    actual_minutes = fields.Integer(
        string="Actual Duration (min)",
        compute="_compute_durations",
        store=False,
        help="Actual duration in minutes.",
    )

    effort_hours = fields.Float(
        string="Effort (Hours)",
        compute="_compute_durations",
        store=False,
        help="Actual effort in hours based on actual duration.",
    )

    sla_deadline = fields.Datetime(
        string="SLA Deadline",
        help="Deadline for SLA commitment (e.g., start or completion).",
        tracking=True,
    )

    sla_target = fields.Selection(
        selection=[("start", "Start On Time"), ("finish", "Finish On Time")],
        string="SLA Target",
        default="finish",
        help="Which KPI the SLA is checking against.",
    )

    sla_met = fields.Boolean(
        string="SLA Met",
        compute="_compute_sla_met",
        store=False,
        help="True when the SLA target is met based on actual timestamps.",
    )

    priority = fields.Selection(
        selection=[
            ("0", "Low"),
            ("1", "Normal"),
            ("2", "High"),
            ("3", "Urgent"),
        ],
        string="Priority",
        default="1",
        index=True,
        help="Operational priority for routing and display.",
        tracking=True,
    )

    allow_overlap = fields.Boolean(
        string="Allow Overlap",
        default=False,
        help="If enabled, overlapping assignments for the same staff are allowed.",
    )

    # =========================================================
    # Compliance (Skill & License)
    # =========================================================
    required_skill_ids = fields.Many2many(
        "clinic.skill",
        "clinic_assignment_skill_rel",
        "assignment_id",
        "skill_id",
        string="Required Skills",
        help="Skills required to perform this assignment.",
    )

    is_skill_compliant = fields.Boolean(
        string="Skill Compliant",
        compute="_compute_compliance",
        store=False,
        help="True if the staff has required skills within validity and grade thresholds.",
    )

    license_required = fields.Boolean(
        string="License Required",
        compute="_compute_license_flags",
        store=False,
        help="True if at least one of the required skills requires an active license.",
    )

    has_active_license = fields.Boolean(
        string="Has Active License",
        compute="_compute_license_flags",
        store=False,
        help="True if staff maintains at least one active license.",
    )

    # =========================================================
    # Status & Tampilan
    # =========================================================
    state = fields.Selection(
        selection=[
            ("draft", "Draft"),
            ("confirmed", "Confirmed"),
            ("in_progress", "In Progress"),
            ("paused", "Paused"),
            ("done", "Done"),
            ("cancelled", "Cancelled"),
            ("closed", "Closed"),  # alias "Done" finalisasi (jika dipakai)
        ],
        string="Status",
        default="draft",
        index=True,
        help="Assignment lifecycle status.",
        tracking=True,
    )

    display_name = fields.Char(
        string="Display Name",
        compute="_compute_display_name",
        store=True,
        help="Composite label including reference, staff, type, patient, and window.",
    )

    color = fields.Integer(
        string="Color",
        help="Optional color index for kanban/calendar views.",
    )

    notes = fields.Text(
        string="Notes",
        help="Additional remarks or instructions.",
    )

    active = fields.Boolean(
        string="Active",
        default=True,
        help="If unchecked, this assignment will be hidden from most views.",
    )

    # =========================================================
    # Konflik & Pemeriksaan Integrasi
    # =========================================================
    conflict_other_assignments = fields.Boolean(
        string="Overlaps Other Assignments",
        compute="_compute_conflicts",
        store=False,
        help="True if overlapping with other assignments of the same staff (when overlap is not allowed).",
    )

    conflict_blocking_availability = fields.Boolean(
        string="Conflicts with Blocking Availability",
        compute="_compute_conflicts",
        store=False,
        help="True if overlapping with blocking availability windows.",
    )

    within_roster = fields.Boolean(
        string="Within Roster Window",
        compute="_compute_within_roster",
        store=False,
        help="True if planned window falls within the linked roster time range.",
    )

    # =========================================================
    # Linkage ke modul lain (opsional/tergantung dependensi)
    # =========================================================
    # incident_ids = fields.Many2many(
    #     "clinic.incident",
    #     "clinic_assignment_incident_rel",
    #     "assignment_id",
    #     "incident_id",
    #     string="Incidents",
    #     help="Incidents associated with this assignment.",
    # )

    # postcare_task_ids = fields.One2many(
    #     "clinic.postcare.task",
    #     "assignment_id",
    #     string="Post-Care Tasks",
    #     help="Post-care tasks created from this assignment.",
    # )

    # =========================================================
    # SQL Constraints
    # =========================================================
    _check_start_before_stop = models.Constraint(
        'CHECK (start < stop)',
        'Planned Start must be earlier than Planned Stop.',
    )

    _assignment_reference_unique = models.Constraint(
        'unique(reference)',
        'Assignment Reference must be unique.',
    )

    # =========================================================
    # Reference Model Selections
    # =========================================================
    # def _ref_location_models(self):
    #     """Daftar model referensi untuk lokasi / konteks operasional."""
    #     return [
    #         ("clinic.room", "Clinic Room"),
    #         ("clinic.queue", "Clinic Queue"),
    #         ("clinic.queue.token", "Queue Token"),
    #         ("clinic.encounter", "Clinical Encounter"),
    #     ]

    # def _ref_procedure_models(self):
    #     """Daftar model referensi untuk prosedur / sesi perawatan."""
    #     return [
    #         ("clinic.procedure", "Clinical Procedure"),
    #         ("clinic.procedure.session", "Treatment Session"),
    #     ]

    # =========================================================
    # Compute Methods
    # =========================================================
    @api.depends("reference", "name", "staff_id.display_name", "assignment_type", "start", "stop")
    def _compute_display_name(self):
        """Compute the assignment label from fields available in this active model."""
        type_selection = dict(self._fields["assignment_type"].selection)
        for rec in self:
            parts = []
            if rec.reference and rec.reference not in ("/",):
                parts.append(f"[{rec.reference}]")
            if rec.name:
                parts.append(rec.name)
            if rec.staff_id:
                parts.append(rec.staff_id.display_name or _("(No Staff)"))
            if rec.assignment_type:
                parts.append(f"→ {type_selection.get(rec.assignment_type, rec.assignment_type)}")
            if rec.start and rec.stop:
                parts.append(
                    f"({fields.Datetime.to_string(rec.start)} → {fields.Datetime.to_string(rec.stop)})"
                )
            rec.display_name = " ".join(parts) if parts else _("Staff Assignment")

    # @api.depends("reference", "staff_id.display_name", "assignment_type", "patient_id.display_name", "start", "stop")
    # def _compute_display_name(self):
    #     for rec in self:
    #         parts = []
    #         if rec.reference and rec.reference not in ("/",):
    #             parts.append(f"[{rec.reference}]")
    #         if rec.staff_id:
    #             parts.append(rec.staff_id.display_name or _("(No Staff)"))
    #         if rec.assignment_type:
    #             parts.append(f"→ {dict(self._fields['assignment_type'].selection).get(rec.assignment_type)}")
    #         if rec.patient_id:
    #             parts.append(f"• {rec.patient_id.display_name}")
    #         if rec.start and rec.stop:
    #             parts.append(f"({fields.Datetime.to_string(rec.start)} → {fields.Datetime.to_string(rec.stop)})")
    #         rec.display_name = " ".join(parts) if parts else _("Staff Assignment")

    def _compute_durations(self):
        for rec in self:
            rec.planned_minutes = 0
            rec.actual_minutes = 0
            rec.effort_hours = 0.0
            if rec.start and rec.stop:
                rec.planned_minutes = max(0, int((rec.stop - rec.start).total_seconds() // 60))
            if rec.actual_start and rec.actual_stop:
                rec.actual_minutes = max(0, int((rec.actual_stop - rec.actual_start).total_seconds() // 60))
                rec.effort_hours = rec.actual_minutes / 60.0

    def _get_staff_active_license(self, staff):
        """Helper: cek ada lisensi aktif pada staff (state active/expiring & belum kadaluarsa)."""
        License = self.env["clinic.staff.license"]
        # Gunakan search_count cepat; asumsi expiry logic pada model lisensi
        return bool(License.sudo().search_count([
            ("staff_id", "=", staff.id),
            ("state", "in", ("active", "expiring")),
        ]))

    # MEMANG DI REMARK - DEPRECATED ERROR
    # @api.depends("required_skill_ids", "staff_id.grade", "staff_id.license_ids.state")
    # def _compute_compliance(self):
    #     """Skill compliance: semua required_skill harus ada di clinic.staff.skill dengan is_compliant=True."""
    #     StaffSkill = self.env["clinic.staff.skill"]
    #     for rec in self:
    #         if not rec.required_skill_ids:
    #             rec.is_skill_compliant = True
    #             continue
    #         ok = True
    #         for skill in rec.required_skill_ids:
    #             has = StaffSkill.sudo().search_count([
    #                 ("staff_id", "=", rec.staff_id.id),
    #                 ("skill_id", "=", skill.id),
    #                 ("state", "=", "valid"),
    #             ])
    #             # Validasi tambahan: is_compliant compute (grade/license/valid window)
    #             if not has:
    #                 ok = False
    #                 break
    #         rec.is_skill_compliant = bool(ok)

    # MEMANG DI REMARK - DEPRECATED ERROR
    # Hilangkan 'required_skill_ids' dari depends untuk menghindari ValueError @depends
    @api.depends("staff_id.grade", "staff_id.license_ids.state")
    def _compute_compliance(self):
        """Skill compliance: semua required_skill harus ada di clinic.staff.skill dengan state 'valid'."""
        StaffSkill = self.env["clinic.staff.skill"]
        for rec in self:
            if not rec.required_skill_ids:
                rec.is_skill_compliant = True
                continue
            ok = True
            for skill in rec.required_skill_ids:
                has = StaffSkill.sudo().search_count([
                    ("staff_id", "=", rec.staff_id.id),
                    ("skill_id", "=", skill.id),
                    ("state", "=", "valid"),
                ])
                if not has:
                    ok = False
                    break
            rec.is_skill_compliant = bool(ok)

    # @api.depends("required_skill_ids.requires_license", "staff_id.license_ids.state")
    # def _compute_license_flags(self):
    #     for rec in self:
    #         rec.license_required = any(skill.requires_license for skill in rec.required_skill_ids)
    #         rec.has_active_license = rec._get_staff_active_license(rec.staff_id) if rec.staff_id else False

    @api.depends("staff_id.license_ids.state")
    def _compute_license_flags(self):
        for rec in self:
            # tetap baca required_skill_ids di body; decorator tidak menyebutnya
            rec.license_required = any(skill.requires_license for skill in rec.required_skill_ids)
            rec.has_active_license = rec._get_staff_active_license(rec.staff_id) if rec.staff_id else False

    def _overlap_domain(self, start_dt, end_dt):
        return [("start", "<", end_dt), ("stop", ">", start_dt)]

    def _availability_conflict(self):
        """Cek konflik dengan availability blocking."""
        Av = self.env.get("clinic.staff.availability")
        AvOcc = self.env.get("clinic.staff.availability.occurrence")
        conflict = False
        for rec in self:
            if not (rec.staff_id and rec.start and rec.stop):
                continue
            try:
                if Av:
                    dom_av = [
                        ("staff_id", "=", rec.staff_id.id),
                        ("is_blocking", "=", True),
                    ] + self._overlap_domain(rec.start, rec.stop)
                    conflict = conflict or bool(Av.sudo().search_count(dom_av))
                if AvOcc:
                    dom_oc = [
                        ("staff_id", "=", rec.staff_id.id),
                        ("is_blocking", "=", True),
                        ("state", "in", ("planned", "applied")),
                    ] + self._overlap_domain(rec.start, rec.stop)
                    conflict = conflict or bool(AvOcc.sudo().search_count(dom_oc))
            except Exception:
                _logger.debug("Availability conflict check skipped for assignment %s", rec.id)
        return conflict

    def _compute_conflicts(self):
        for rec in self:
            # Overlap vs other assignments (same staff), except cancelled/done/closed
            dom_as = [
                ("id", "!=", rec.id),
                ("staff_id", "=", rec.staff_id.id),
                ("state", "in", ("draft", "confirmed", "in_progress", "paused")),
            ] + self._overlap_domain(rec.start, rec.stop)
            try:
                other_overlap = bool(self.sudo().search_count(dom_as))
            except Exception:
                other_overlap = False
            rec.conflict_other_assignments = (other_overlap and not rec.allow_overlap)

            # Availability blocking conflict
            rec.conflict_blocking_availability = False
            try:
                rec.conflict_blocking_availability = bool(self.browse(rec.id)._availability_conflict())
            except Exception:
                pass

    def _compute_within_roster(self):
        for rec in self:
            if rec.roster_id and rec.start and rec.stop:
                rec.within_roster = (rec.start >= rec.roster_id.start and rec.stop <= rec.roster_id.stop)
            else:
                rec.within_roster = False

    @api.depends("sla_target", "sla_deadline", "actual_start", "actual_stop")
    def _compute_sla_met(self):
        for rec in self:
            met = False
            if rec.sla_target == "start" and rec.sla_deadline and rec.actual_start:
                met = rec.actual_start <= rec.sla_deadline
            elif rec.sla_target == "finish" and rec.sla_deadline and rec.actual_stop:
                met = rec.actual_stop <= rec.sla_deadline
            rec.sla_met = met

    # =========================================================
    # Constraints
    # =========================================================
    @api.constrains("start", "stop")
    def _check_planned_window(self):
        for rec in self:
            if rec.start and rec.stop and rec.stop <= rec.start:
                raise ValidationError(_("Planned Stop must be later than Planned Start."))

    @api.constrains("actual_start", "actual_stop")
    def _check_actual_window(self):
        for rec in self:
            if rec.actual_start and rec.actual_stop and rec.actual_stop <= rec.actual_start:
                raise ValidationError(_("Actual Stop must be later than Actual Start."))

    @api.constrains("staff_id", "start", "stop", "state", "allow_overlap")
    def _check_overlap_other_assignments(self):
        """Larangan overlap assignment aktif kecuali allow_overlap=True."""
        for rec in self.filtered(lambda r: r.staff_id and r.start and r.stop and not r.allow_overlap):
            dom = [
                ("id", "!=", rec.id),
                ("staff_id", "=", rec.staff_id.id),
                ("state", "in", ("draft", "confirmed", "in_progress", "paused")),
            ] + self._overlap_domain(rec.start, rec.stop)
            if self.search_count(dom):
                raise ValidationError(_("This assignment overlaps with another active assignment for the same staff."))

    # =========================================================
    # CRUD Overrides
    # =========================================================
    @api.model_create_multi
    def create(self, vals_list):
        """Set reference dari sequence, lakukan validasi ringan, dan schedule activity jika perlu."""
        for vals in vals_list:
            if not vals.get("reference") or vals.get("reference") in ("/",):
                vals["reference"] = self.env["ir.sequence"].next_by_code("clinic.staff.assignment") or "/"
        records = super().create(vals_list)

        # Jadwalkan activity jika compliance belum terpenuhi atau ada konflik availability
        for rec in records:
            # Compliance basic
            if rec.required_skill_ids and not rec.is_skill_compliant:
                rec.activity_schedule(
                    "mail.mail_activity_data_todo",
                    summary=_("Validate skill compliance"),
                    note=_("Staff may not meet all required skills for this assignment. Please review."),
                )
            if rec.license_required and not rec.has_active_license:
                rec.activity_schedule(
                    "mail.mail_activity_data_todo",
                    summary=_("Ensure active professional license"),
                    note=_("At least one required skill needs an active license. Please review staff licenses."),
                )
            # Availability blocking
            if rec.conflict_blocking_availability:
                rec.activity_schedule(
                    "mail.mail_activity_data_todo",
                    summary=_("Conflicts with blocking availability"),
                    note=_("This assignment overlaps with blocking availability windows. Please resolve."),
                )
        return records

    def write(self, vals):
        res = super().write(vals)
        # Re-check & notify on critical changes
        if {"start", "stop", "required_skill_ids", "staff_id"}.intersection(vals.keys()):
            for rec in self:
                if rec.required_skill_ids and not rec.is_skill_compliant:
                    rec.activity_schedule(
                        "mail.mail_activity_data_todo",
                        summary=_("Validate skill compliance"),
                        note=_("Staff may not meet all required skills for this assignment. Please review."),
                    )
                if rec.license_required and not rec.has_active_license:
                    rec.activity_schedule(
                        "mail.mail_activity_data_todo",
                        summary=_("Ensure active professional license"),
                        note=_("At least one required skill needs an active license. Please review staff licenses."),
                    )
                if rec.conflict_blocking_availability:
                    rec.activity_schedule(
                        "mail.mail_activity_data_todo",
                        summary=_("Conflicts with blocking availability"),
                        note=_("This assignment overlaps with blocking availability windows. Please resolve."),
                    )
        return res

    # =========================================================
    # Actions (Workflow)
    # =========================================================
    def action_confirm(self):
        """Konfirmasi assignment: cek compliance & konflik mendasar."""
        for rec in self:
            if rec.state not in ("draft",):
                continue
            # Cek eligibility staff (dari model staff)
            rec.staff_id.ensure_clinical_eligibility()
            # Cek skill compliance minimal
            if rec.required_skill_ids and not rec.is_skill_compliant:
                raise ValidationError(_("Staff does not meet required skills for this assignment."))
            # Cek license jika perlu
            if rec.license_required and not rec.has_active_license:
                raise ValidationError(_("Active professional license is required for this assignment."))
            # Cek availability blocking
            if rec.conflict_blocking_availability:
                raise ValidationError(_("This assignment conflicts with blocking availability windows."))
            # Cek roster (opsional tapi disarankan)
            if rec.roster_id and not rec.within_roster:
                raise ValidationError(_("Planned window must be within the linked roster time range."))
            rec.state = "confirmed"
            rec.message_post(body=_("Assignment confirmed."))
        return True

    def action_start(self):
        """Mulai pengerjaan assignment."""
        for rec in self:
            if rec.state not in ("confirmed", "paused"):
                continue
            if not rec.actual_start:
                rec.actual_start = fields.Datetime.now()
            rec.state = "in_progress"
            rec.message_post(body=_("Assignment started."))
        return True

    def action_pause(self):
        """Jeda pengerjaan (opsional)."""
        for rec in self:
            if rec.state != "in_progress":
                continue
            rec.state = "paused"
            rec.message_post(body=_("Assignment paused."))
        return True

    def action_done(self):
        """Selesaikan assignment."""
        for rec in self:
            if rec.state not in ("in_progress", "paused", "confirmed"):
                continue
            if not rec.actual_stop:
                rec.actual_stop = fields.Datetime.now()
            rec.state = "done"
            # Tandai closed untuk konsistensi lifecycle (opsional)
            rec.message_post(body=_("Assignment completed."))
        return True

    def action_cancel(self):
        """Batalkan assignment."""
        for rec in self:
            if rec.state in ("done", "closed"):
                raise ValidationError(_("Completed assignments cannot be cancelled."))
            rec.state = "cancelled"
            rec.message_post(body=_("Assignment cancelled."))
        return True

    def action_close(self):
        """Tutup assignment (alias finalisasi setelah 'done')."""
        for rec in self:
            if rec.state != "done":
                continue
            rec.state = "closed"
            rec.message_post(body=_("Assignment closed."))
        return True

    # =========================================================
    # Reassignment / Helpers
    # =========================================================
    def reassign_to(self, new_staff_id):
        """Re-assign ke staff berbeda (dipanggil dari wizard/batch).
        - Memvalidasi eligibility staff baru.
        """
        Staff = self.env["clinic.staff"]
        new_staff = Staff.browse(new_staff_id).exists()
        if not new_staff:
            raise ValidationError(_("Target staff not found."))

        for rec in self:
            new_staff.ensure_clinical_eligibility()
            # Optional: reset compliance flag notifikasi
            rec.write({"staff_id": new_staff.id})
            rec.message_post(body=_("Assignment reassigned to %s.") % (new_staff.display_name,))
        return True

    # =========================================================
    # Name get
    # =========================================================
    def name_get(self):
        res = []
        for rec in self:
            res.append((rec.id, rec.display_name or rec.name or rec.reference or _("Assignment")))
        return res
