

# -*- coding: utf-8 -*-
# ClinicOne - Clinical Staff (Nurse & Therapist) Management
# File: staff_workload.py
#
# Catatan (ID):
# - Menyediakan rangka kerja Workload yang terhubung dengan Roster, Assignment, dan Availability.
# - Kebijakan Workload (FTE/week) fleksibel berdasarkan role, grade, dan branch.
# - Perhitungan memisahkan Planned vs Actual, serta Leave/Unavailable dan Overtime.
# - Menggunakan soft lookup (env.get) agar aman ketika modul lain belum aktif.

from odoo import api, fields, models, _
from odoo.exceptions import ValidationError
from datetime import datetime, timedelta
import logging

_logger = logging.getLogger(__name__)


# ============================================================
# Utilities
# ============================================================

def _overlap_minutes(a_start, a_stop, b_start, b_stop):
    """Hitung menit overlap dua interval waktu [start, stop)."""
    if not (a_start and a_stop and b_start and b_stop):
        return 0
    start = max(a_start, b_start)
    stop = min(a_stop, b_stop)
    if stop <= start:
        return 0
    return int((stop - start).total_seconds() // 60)


def _to_hours(minutes):
    return round(float(minutes) / 60.0, 2)


# ============================================================
# Workload Policy (Master)
# ============================================================
class ClinicWorkloadPolicy(models.Model):
    _name = "clinic.workload.policy"
    _description = "Workload Policy"
    _rec_name = "name"
    _order = "sequence, date_start desc, id desc"

    sequence = fields.Integer(
        string="Sequence",
        default=10,
        help="Ordering of policies when multiple entries could apply."
    )

    name = fields.Char(
        string="Policy Name",
        required=True,
        translate=True,
        help="Human-readable name of this workload policy."
    )

    code = fields.Char(
        string="Code",
        required=True,
        copy=False,
        default="/",
        index=True,
        help="Unique code generated by sequence for the policy."
    )

    company_id = fields.Many2one(
        "res.company",
        string="Company",
        default=lambda self: self.env.company,
        help="Company where this policy applies."
    )

    # Cakupan (Scope)
    role_scope = fields.Selection(
        selection=[
            ("any", "Any"),
            ("nurse", "Nurse"),
            ("therapist", "Therapist"),
            ("doctor", "Doctor"),
            ("other", "Other"),
        ],
        string="Role Scope",
        default="any",
        index=True,
        help="Limit this policy to staff with a specific role, or apply to any role."
    )

    grade_scope = fields.Selection(
        selection=[
            ("any", "Any"),
            ("junior", "Junior"),
            ("mid", "Mid"),
            ("senior", "Senior"),
            ("lead", "Lead"),
            ("principal", "Principal"),
        ],
        string="Grade Scope",
        default="any",
        index=True,
        help="Limit this policy to a specific grade, or apply to any grade."
    )

    branch_id = fields.Many2one(
        "clinic.branch",
        string="Branch Scope",
        help="If set, this policy applies only to this branch."
    )

    # Kapasitas dasar
    weekly_capacity_hours = fields.Float(
        string="Weekly Capacity (Hours)",
        required=True,
        default=40.0,
        help="Nominal FTE weekly capacity in hours (e.g., 40.0)."
    )

    # Buffer & threshold
    buffer_percent = fields.Float(
        string="Buffer (%)",
        default=10.0,
        help="Buffer percentage for overload tolerance (e.g., 10%)."
    )

    warn_under_util_pct = fields.Float(
        string="Warn Under-Utilization (%)",
        default=60.0,
        help="Warn when planned/actual utilization falls below this percentage."
    )

    warn_over_util_pct = fields.Float(
        string="Warn Over-Utilization (%)",
        default=110.0,
        help="Warn when planned/actual utilization exceeds this percentage."
    )

    include_overtime = fields.Boolean(
        string="Include Overtime",
        default=True,
        help="If enabled, hours beyond roster/assignment windows will be counted as overtime if captured."
    )

    # Periode berlaku
    date_start = fields.Date(
        string="Valid From",
        help="Start date when the policy becomes effective (inclusive)."
    )

    date_end = fields.Date(
        string="Valid Until",
        help="End date when the policy stops being effective (inclusive)."
    )

    active = fields.Boolean(
        string="Active",
        default=True,
        help="If unchecked, this policy is ignored."
    )

    _workload_policy_code_unique = models.Constraint(
        'unique(code)',
        'Policy Code must be unique.',
    )

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get("code") or vals.get("code") in ("/",):
                vals["code"] = self.env["ir.sequence"].next_by_code("clinic.workload.policy") or "/"
        return super().create(vals_list)

    # Seleksi policy yang applicable untuk staff & tanggal
    def is_applicable(self, staff, d_from=None, d_to=None):
        self.ensure_one()
        if not self.active:
            return False
        # Role
        if self.role_scope != "any" and staff.role != self.role_scope:
            return False
        # Grade
        if self.grade_scope != "any" and (staff.grade or "any") != self.grade_scope:
            return False
        # Branch
        if self.branch_id and staff.branch_id and (self.branch_id.id != staff.branch_id.id):
            return False
        # Date range (overlap hari)
        if self.date_start and d_to and fields.Date.to_date(self.date_start) > fields.Date.to_date(d_to):
            return False
        if self.date_end and d_from and fields.Date.to_date(self.date_end) < fields.Date.to_date(d_from):
            return False
        return True


# ============================================================
# Workload Summary (Per Staff Per Period)
# ============================================================
class ClinicStaffWorkload(models.Model):
    _name = "clinic.staff.workload"
    _description = "Staff Workload Summary"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _rec_name = "display_name"
    _order = "date_from desc, staff_id, id desc"

    # Identitas & periode
    staff_id = fields.Many2one(
        "clinic.staff",
        string="Staff",
        required=True,
        index=True,
        ondelete="cascade",
        help="Staff member whose workload is summarized."
    )

    company_id = fields.Many2one(
        "res.company",
        string="Company",
        related="staff_id.company_id",
        store=True,
        readonly=True
    )

    branch_id = fields.Many2one(
        "clinic.branch",
        string="Branch",
        help="Operational branch context for this period summary."
    )

    period_type = fields.Selection(
        selection=[
            ("week", "Week"),
            ("month", "Month"),
            ("custom", "Custom"),
        ],
        string="Period Type",
        required=True,
        default="week",
        index=True,
        help="Defines how to interpret the date range for capacity scaling."
    )

    date_from = fields.Date(
        string="From",
        required=True,
        index=True,
        help="Start date of the summarized period (inclusive)."
    )

    date_to = fields.Date(
        string="To",
        required=True,
        index=True,
        help="End date of the summarized period (inclusive)."
    )

    # Kebijakan
    policy_id = fields.Many2one(
        "clinic.workload.policy",
        string="Workload Policy",
        help="Policy applied to compute capacity and thresholds for this period."
    )

    # Kapasitas & perhitungan jam
    capacity_hours = fields.Float(
        string="Capacity (Hours)",
        help="Scaled capacity hours for the date range using the applied policy."
    )

    planned_hours = fields.Float(
        string="Planned Hours",
        help="Planned working hours (e.g., from rosters and planned assignments)."
    )

    actual_hours = fields.Float(
        string="Actual Hours",
        help="Actual effort hours (typically from actual assignment timings; fallback to rosters when missing)."
    )

    leave_hours = fields.Float(
        string="Leave/Unavailable Hours",
        help="Hours marked as leave or unavailable that overlap with the planning window."
    )

    overtime_hours = fields.Float(
        string="Overtime Hours",
        help="Overtime beyond planned windows (if captured)."
    )

    # Utilization metrics
    utilization_planned = fields.Float(
        string="Planned Utilization (%)",
        help="Planned hours / capacity * 100."
    )

    utilization_actual = fields.Float(
        string="Actual Utilization (%)",
        help="Actual hours / capacity * 100."
    )

    # Flags
    under_utilized = fields.Boolean(
        string="Under-Utilized",
        help="True if utilization falls below policy threshold."
    )

    over_utilized = fields.Boolean(
        string="Over-Utilized",
        help="True if utilization exceeds policy threshold (with buffer)."
    )

    # Tautan detail
    line_ids = fields.One2many(
        "clinic.staff.workload.line",
        "workload_id",
        string="Details",
        help="Detailed source lines contributing to the workload."
    )

    # Info tampilan
    display_name = fields.Char(
        string="Display Name",
        compute="_compute_display_name",
        store=True,
        help="Composite label for this workload summary."
    )

    notes = fields.Text(
        string="Notes",
        help="Additional remarks, suggestions, or manual adjustments."
    )

    _date_order_valid = models.Constraint(
        'CHECK (date_from <= date_to)',
        'Date From must be earlier or equal to Date To.',
    )

    _unique_period_per_staff = models.Constraint(
        'unique(staff_id, date_from, date_to, period_type)',
        'Workload summary for the same staff and period must be unique.',
    )

    # --------------------------------------------------------
    # Compute
    # --------------------------------------------------------
    @api.depends("staff_id.display_name", "period_type", "date_from", "date_to")
    def _compute_display_name(self):
        for rec in self:
            period = dict(self._fields["period_type"].selection).get(rec.period_type)
            parts = [
                rec.staff_id.display_name or _("(No Staff)"),
                f"- {period}" if period else "",
                f"[{rec.date_from} → {rec.date_to}]",
            ]
            rec.display_name = " ".join([p for p in parts if p])

    # --------------------------------------------------------
    # Helper: Ambil policy applicable
    # --------------------------------------------------------
    def _pick_applicable_policy(self):
        Policy = self.env["clinic.workload.policy"]
        policies = Policy.search([("active", "=", True)], order="sequence, id")
        for rec in self:
            chosen = None
            for p in policies:
                if p.is_applicable(rec.staff_id, rec.date_from, rec.date_to):
                    chosen = p
                    break
            rec.policy_id = chosen

    # --------------------------------------------------------
    # Perhitungan kapasitas berdasarkan policy & panjang periode
    # --------------------------------------------------------
    def _compute_capacity_hours(self):
        for rec in self:
            if not rec.policy_id:
                rec.capacity_hours = 0.0
                continue
            # Skala berdasar jumlah hari dalam periode / 7 * weekly_capacity_hours
            d_from = fields.Date.to_date(rec.date_from)
            d_to = fields.Date.to_date(rec.date_to)
            days = (d_to - d_from).days + 1
            weekly = rec.policy_id.weekly_capacity_hours or 0.0
            # Asumsi kalender sederhana tanpa holiday: capacity ~ weekly * (days / 7)
            rec.capacity_hours = round(weekly * (float(days) / 7.0), 2)

    # --------------------------------------------------------
    # Sumber data (Roster/Assignment/Availability)
    # --------------------------------------------------------
    def _gather_source_minutes(self):
        """Kumpulkan menit planned/actual/leave per periode dari Roster, Assignment, Availability."""
        Roster = self.env.get("clinic.staff.roster")
        Assign = self.env.get("clinic.staff.assignment")
        Av = self.env.get("clinic.staff.availability")
        AvOcc = self.env.get("clinic.staff.availability.occurrence")

        for rec in self:
            if not (rec.staff_id and rec.date_from and rec.date_to):
                rec.planned_hours = rec.actual_hours = rec.leave_hours = rec.overtime_hours = 0.0
                continue

            # Range waktu (gunakan UTC; Date → Datetime 00:00 sampai 23:59:59)
            start_dt = fields.Datetime.to_datetime(f"{rec.date_from} 00:00:00")
            end_dt = fields.Datetime.to_datetime(f"{rec.date_to} 23:59:59")

            planned_min = 0
            actual_min = 0
            leave_min = 0
            overtime_min = 0

            # ---- Roster: planned hours
            if Roster:
                ros = Roster.sudo().search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("state", "in", ("published", "in_progress", "completed")),
                    ("start", "<=", end_dt),
                    ("stop", ">=", start_dt),
                ])
                for r in ros:
                    planned_min += _overlap_minutes(r.start, r.stop, start_dt, end_dt)

            # ---- Assignment: planned vs actual
            if Assign:
                asg = Assign.sudo().search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("state", "not in", ("cancelled", "closed")),
                    ("start", "<=", end_dt),
                    ("stop", ">=", start_dt),
                ])
                for a in asg:
                    # planned
                    planned_min += _overlap_minutes(a.start, a.stop, start_dt, end_dt)
                    # actual (jika tersedia; fallback planned jika in_progress/done tanpa actual)
                    if a.actual_start and a.actual_stop:
                        actual_min += _overlap_minutes(a.actual_start, a.actual_stop, start_dt, end_dt)
                    elif a.state in ("in_progress", "done") and (a.actual_start or a.actual_stop):
                        # partial actual: gunakan timestamp yang ada + planned sisi lain
                        st = a.actual_start or a.start
                        sp = a.actual_stop or a.stop
                        actual_min += _overlap_minutes(st, sp, start_dt, end_dt)

            # ---- Availability: Leave/Unavailable
            def add_leave_interval(s, e):
                nonlocal leave_min
                leave_min += _overlap_minutes(s, e, start_dt, end_dt)

            if Av:
                avs = Av.sudo().search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("is_blocking", "=", True),
                    ("availability_type", "in", ("leave", "unavailable")),
                    ("start", "<=", end_dt),
                    ("stop", ">=", start_dt),
                ])
                for av in avs:
                    add_leave_interval(av.start, av.stop)

            if AvOcc:
                ovs = AvOcc.sudo().search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("is_blocking", "=", True),
                    ("availability_type", "in", ("leave", "unavailable")),
                    ("state", "in", ("planned", "applied")),
                    ("start", "<=", end_dt),
                    ("stop", ">=", start_dt),
                ])
                for ov in ovs:
                    add_leave_interval(ov.start, ov.stop)

            # ---- Overtime: heuristik (optional)
            # Jika actual > planned dan policy include_overtime -> selisih dianggap overtime.
            if actual_min > planned_min:
                overtime_min = actual_min - planned_min

            rec.planned_hours = _to_hours(planned_min)
            rec.actual_hours = _to_hours(actual_min) if actual_min else (rec.planned_hours or 0.0)
            rec.leave_hours = _to_hours(leave_min)
            rec.overtime_hours = _to_hours(overtime_min)

    # --------------------------------------------------------
    # Hitung utilization & flags
    # --------------------------------------------------------
    def _compute_utilization_and_flags(self):
        for rec in self:
            cap = rec.capacity_hours or 0.0
            pol = rec.policy_id
            if cap <= 0:
                rec.utilization_planned = 0.0
                rec.utilization_actual = 0.0
                rec.under_utilized = False
                rec.over_utilized = False
                continue

            rec.utilization_planned = round((rec.planned_hours / cap) * 100.0, 2)
            rec.utilization_actual = round((rec.actual_hours / cap) * 100.0, 2)

            under_thr = (pol.warn_under_util_pct if pol else 0.0) or 0.0
            over_thr = (pol.warn_over_util_pct if pol else 0.0) or 100.0
            buffer_pct = (pol.buffer_percent if pol else 0.0) or 0.0

            rec.under_utilized = rec.utilization_actual < under_thr
            # Over-utilized jika planned/actual melewati threshold; buffer membuat ambang lebih permisif
            permitted = 100.0 + buffer_pct
            check_value = max(rec.utilization_planned, rec.utilization_actual)
            rec.over_utilized = check_value > max(over_thr, permitted)

    # --------------------------------------------------------
    # Public API
    # --------------------------------------------------------
    def recompute_workload(self, generate_lines=True, replace_lines=True):
        """Hitung ulang policy, capacity, sumber jam, dan utilization. Opsional generate workload lines."""
        Line = self.env["clinic.staff.workload.line"].sudo()
        for rec in self:
            # Policy & capacity
            rec._pick_applicable_policy()
            rec._compute_capacity_hours()
            # Hours breakdown
            rec._gather_source_minutes()
            # Utilization & flags
            rec._compute_utilization_and_flags()

            if generate_lines:
                if replace_lines and rec.line_ids:
                    rec.line_ids.unlink()
                rec._generate_detail_lines()

        return True

    def _generate_detail_lines(self):
        """Bangun baris detail dari sumber Roster/Assignment/Availability untuk audit."""
        Roster = self.env.get("clinic.staff.roster")
        Assign = self.env.get("clinic.staff.assignment")
        Av = self.env.get("clinic.staff.availability")
        AvOcc = self.env.get("clinic.staff.availability.occurrence")
        Line = self.env["clinic.staff.workload.line"].sudo()

        for rec in self:
            start_dt = fields.Datetime.to_datetime(f"{rec.date_from} 00:00:00")
            end_dt = fields.Datetime.to_datetime(f"{rec.date_to} 23:59:59")
            vals_batch = []

            # Roster
            if Roster:
                ros = Roster.sudo().search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("state", "in", ("published", "in_progress", "completed")),
                    ("start", "<=", end_dt),
                    ("stop", ">=", start_dt),
                ])
                for r in ros:
                    minutes = _overlap_minutes(r.start, r.stop, start_dt, end_dt)
                    if minutes > 0:
                        vals_batch.append({
                            "workload_id": rec.id,
                            "source_type": "roster",
                            "source_ref": f"{r._name},{r.id}",
                            "start": r.start,
                            "stop": r.stop,
                            "minutes": minutes,
                            "state": r.state,
                            "branch_id": r.branch_id.id if r.branch_id else False,
                        })

            # Assignment
            if Assign:
                asg = Assign.sudo().search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("state", "not in", ("cancelled", "closed")),
                    ("start", "<=", end_dt),
                    ("stop", ">=", start_dt),
                ])
                for a in asg:
                    pmin = _overlap_minutes(a.start, a.stop, start_dt, end_dt)
                    amin = 0
                    if a.actual_start and a.actual_stop:
                        amin = _overlap_minutes(a.actual_start, a.actual_stop, start_dt, end_dt)
                    elif a.state in ("in_progress", "done") and (a.actual_start or a.actual_stop):
                        st = a.actual_start or a.start
                        sp = a.actual_stop or a.stop
                        amin = _overlap_minutes(st, sp, start_dt, end_dt)

                    if pmin > 0:
                        vals_batch.append({
                            "workload_id": rec.id,
                            "source_type": "assignment_planned",
                            "source_ref": f"{a._name},{a.id}",
                            "start": a.start,
                            "stop": a.stop,
                            "minutes": pmin,
                            "state": a.state,
                            "branch_id": a.branch_id.id if a.branch_id else False,
                        })
                    if amin > 0:
                        vals_batch.append({
                            "workload_id": rec.id,
                            "source_type": "assignment_actual",
                            "source_ref": f"{a._name},{a.id}",
                            "start": a.actual_start or a.start,
                            "stop": a.actual_stop or a.stop,
                            "minutes": amin,
                            "state": a.state,
                            "branch_id": a.branch_id.id if a.branch_id else False,
                        })

            # Availability (Leave/Unavailable)
            def add_av_line(src, s, e, minutes, state=None, branch=None):
                if minutes <= 0:
                    return
                vals_batch.append({
                    "workload_id": rec.id,
                    "source_type": "leave",
                    "source_ref": src,
                    "start": s,
                    "stop": e,
                    "minutes": minutes,
                    "state": state or "planned",
                    "branch_id": branch or False,
                })

            if Av:
                avs = Av.sudo().search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("is_blocking", "=", True),
                    ("availability_type", "in", ("leave", "unavailable")),
                    ("start", "<=", end_dt),
                    ("stop", ">=", start_dt),
                ])
                for av in avs:
                    m = _overlap_minutes(av.start, av.stop, start_dt, end_dt)
                    add_av_line(f"{av._name},{av.id}", av.start, av.stop, m, branch=av.branch_id.id if av.branch_id else False)

            if AvOcc:
                ovs = AvOcc.sudo().search([
                    ("staff_id", "=", rec.staff_id.id),
                    ("is_blocking", "=", True),
                    ("availability_type", "in", ("leave", "unavailable")),
                    ("state", "in", ("planned", "applied")),
                    ("start", "<=", end_dt),
                    ("stop", ">=", start_dt),
                ])
                for ov in ovs:
                    m = _overlap_minutes(ov.start, ov.stop, start_dt, end_dt)
                    add_av_line(f"{ov._name},{ov.id}", ov.start, ov.stop, m, state=ov.state, branch=ov.branch_id.id if ov.branch_id else False)

            if vals_batch:
                Line.create(vals_batch)

    # --------------------------------------------------------
    # Actions
    # --------------------------------------------------------
    def action_recompute(self):
        """Tombol UI: Recompute workload & (re)generate detail lines."""
        self.recompute_workload(generate_lines=True, replace_lines=True)
        for rec in self:
            rec.message_post(body=_("Workload recomputed."))
        return True

    def action_open_lines(self):
        self.ensure_one()
        return {
            "name": _("Workload Details"),
            "type": "ir.actions.act_window",
            "res_model": "clinic.staff.workload.line",
            "view_mode": "list,form",
            "domain": [("workload_id", "=", self.id)],
            "context": {"default_workload_id": self.id},
        }

    def action_open_rosters(self):
        self.ensure_one()
        Roster = self.env.get("clinic.staff.roster")
        if not Roster:
            return False
        start_dt = fields.Datetime.to_datetime(f"{self.date_from} 00:00:00")
        end_dt = fields.Datetime.to_datetime(f"{self.date_to} 23:59:59")
        return {
            "name": _("Rosters"),
            "type": "ir.actions.act_window",
            "res_model": "clinic.staff.roster",
            "view_mode": "calendar,list,form,gantt",
            "domain": [
                ("staff_id", "=", self.staff_id.id),
                ("start", "<=", end_dt),
                ("stop", ">=", start_dt),
            ],
        }

    def action_open_assignments(self):
        self.ensure_one()
        Assign = self.env.get("clinic.staff.assignment")
        if not Assign:
            return False
        start_dt = fields.Datetime.to_datetime(f"{self.date_from} 00:00:00")
        end_dt = fields.Datetime.to_datetime(f"{self.date_to} 23:59:59")
        return {
            "name": _("Assignments"),
            "type": "ir.actions.act_window",
            "res_model": "clinic.staff.assignment",
            "view_mode": "list,form,kanban",
            "domain": [
                ("staff_id", "=", self.staff_id.id),
                ("start", "<=", end_dt),
                ("stop", ">=", start_dt),
            ],
        }

    def action_open_availability(self):
        self.ensure_one()
        Av = self.env.get("clinic.staff.availability")
        if not Av:
            return False
        start_dt = fields.Datetime.to_datetime(f"{self.date_from} 00:00:00")
        end_dt = fields.Datetime.to_datetime(f"{self.date_to} 23:59:59")
        return {
            "name": _("Availability"),
            "type": "ir.actions.act_window",
            "res_model": "clinic.staff.availability",
            "view_mode": "calendar,list,form",
            "domain": [
                ("staff_id", "=", self.staff_id.id),
                ("start", "<=", end_dt),
                ("stop", ">=", start_dt),
            ],
        }

    # --------------------------------------------------------
    # Name get
    # --------------------------------------------------------
    def name_get(self):
        res = []
        for rec in self:
            res.append((rec.id, rec.display_name or _("Workload")))
        return res


# ============================================================
# Workload Detail Line (Audit)
# ============================================================
class ClinicStaffWorkloadLine(models.Model):
    _name = "clinic.staff.workload.line"
    _description = "Staff Workload Line"
    _order = "start, id"

    workload_id = fields.Many2one(
        "clinic.staff.workload",
        string="Workload",
        required=True,
        index=True,
        ondelete="cascade"
    )

    company_id = fields.Many2one(
        "res.company",
        string="Company",
        related="workload_id.company_id",
        store=True,
        readonly=True
    )

    branch_id = fields.Many2one(
        "clinic.branch",
        string="Branch",
        help="Branch context of the source record."
    )

    source_type = fields.Selection(
        selection=[
            ("roster", "Roster"),
            ("assignment_planned", "Assignment (Planned)"),
            ("assignment_actual", "Assignment (Actual)"),
            ("leave", "Leave/Unavailable"),
        ],
        string="Source Type",
        required=True,
        index=True
    )

    source_ref = fields.Char(
        string="Source",
        help="Technical reference '<model>,<id>' to the source record."
    )

    start = fields.Datetime(
        string="Start",
        required=True,
        index=True
    )

    stop = fields.Datetime(
        string="Stop",
        required=True,
        index=True
    )

    minutes = fields.Integer(
        string="Minutes",
        required=True,
        help="Minutes contributing to the workload from this source record."
    )

    hours = fields.Float(
        string="Hours",
        compute="_compute_hours",
        store=False
    )

    state = fields.Char(
        string="State",
        help="State of the source record at the time of capturing."
    )

    note = fields.Char(
        string="Note",
        help="Optional short note or tag."
    )

    def _compute_hours(self):
        for rec in self:
            rec.hours = _to_hours(rec.minutes)

    # Quick smart actions
    def action_open_source(self):
        """Buka source record (jika model tersedia)."""
        self.ensure_one()
        if not self.source_ref or "," not in self.source_ref:
            return False
        model, rec_id = self.source_ref.split(",", 1)
        try:
            rec_id_int = int(rec_id)
        except Exception:
            return False

        Model = self.env.get(model)
        if not Model:
            return False
        if not Model.browse(rec_id_int).exists():
            return False

        return {
            "name": _("Source Record"),
            "type": "ir.actions.act_window",
            "res_model": model,
            "view_mode": "form",
            "res_id": rec_id_int,
            "target": "current",
        }

