
# -*- coding: utf-8 -*-
{
    "name": "ClinicOne — Treatment Package Management",
    "summary": "Enterprise treatment packages, pricing, allocation, redemption, vouchers, and scheduling integration",
    "version": "19.0.3.0.0",
    "category": "ClinicOne/Clinical Operations",
    "author": "ClinicOne",
    "license": "LGPL-3",
    "application": True,
    "installable": True,
    "auto_install": False,
    "depends": [
        "base",
        "mail",
        "contacts",
        "product",
        "uom",
        "sale",
        "account",
        "stock",
        "clinic_base",
        "clinic_audit",
        "clinic_branch",
        "clinic_staff",
        "clinic_room_device",
        "clinic_treatment_catalog",
        "clinic_patient",
        "clinic_doctor",
        "clinic_queue_room",
        "clinic_inventory",
        "clinic_booking",
        "clinic_triage_vitals",
        "clinic_consent_legal",
        "clinic_encounter",
        "clinic_emar",
        "clinic_imaging",
        "clinic_care_plan",
    ],
    "data": [
        "security/clinic_package_security.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/cron_data.xml",
        "views/package_views.xml",
        "views/pricing_views.xml",
        "views/policy_views.xml",
        "views/benefit_views.xml",
        "views/allocation_views.xml",
        "views/usage_views.xml",
        "views/voucher_views.xml",
        "views/integration_event_views.xml",
        "views/res_partner_views.xml",
        "data/optional_view_bridge.xml",
        "views/res_config_settings_views.xml",
        "wizard/package_redeem_wizard_views.xml",
        "wizard/package_transfer_wizard_views.xml",
        "views/menu_views.xml",
    ],
}
