# -*- coding: utf-8 -*-
# File: clinic_billing/models/billing_payment.py
# License: LGPL-3

from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError


# =============================================================================
# Helpers
# =============================================================================

def _float_is_zero(amount, currency):
    """Currency-aware zero check."""
    if not currency:
        return abs(amount) < 1e-6
    return currency.is_zero(amount)


# =============================================================================
# Payment (Header)
# =============================================================================
class ClinicBillingPayment(models.Model):
    """
    Clinic Billing Payment
    ----------------------
    Payment document with split lines that feed Accounting (account.payment)
    and reconcile with the Accounting Invoice (account.move) of the parent
    clinic.billing.invoice.

    Design goals:
    - Support split payment methods (cash, transfer, card, e-wallet, membership, insurance).
    - Create & post account.payment per line (by journal) then reconcile to invoice.
    - Provide soft hooks to membership/insurance/gateway/audit modules.
    - No circular dependency with other ClinicOne modules.
    """
    _name = "clinic.billing.payment"
    _description = "Clinic Billing Payment"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _order = "id desc"
    _rec_name = "name"

    # ---------------------------------------------------------------------
    # Identity & linkage
    # ---------------------------------------------------------------------
    name = fields.Char(
        string="Payment Number",
        default="/",
        copy=False,
        index=True,
        tracking=True,
        help="Sequence number of this clinic payment."
    )
    invoice_id = fields.Many2one(
        "clinic.billing.invoice",
        string="Clinic Invoice",
        required=True,
        index=True,
        ondelete="cascade",
        tracking=True,
        help="Clinic invoice for which this payment is registered."
    )
    move_id = fields.Many2one(
        related="invoice_id.move_id",
        string="Accounting Invoice",
        store=True,
        readonly=True,
        help="Linked accounting invoice (account.move)."
    )
    partner_id = fields.Many2one(
        related="invoice_id.patient_id",
        string="Patient",
        store=True,
        readonly=True
    )
    company_id = fields.Many2one(
        related="invoice_id.company_id",
        string="Company",
        store=True,
        readonly=True
    )
    currency_id = fields.Many2one(
        related="invoice_id.currency_id",
        string="Currency",
        store=True,
        readonly=True
    )

    date = fields.Date(
        string="Payment Date",
        default=lambda self: fields.Date.context_today(self),
        required=True,
        tracking=True
    )
    state = fields.Selection(
        [
            ("draft", "Draft"),
            ("confirmed", "Confirmed"),
            ("posted", "Posted"),
            ("reconciled", "Reconciled"),
            ("cancelled", "Cancelled"),
            ("failed", "Failed"),
        ],
        string="Status",
        default="draft",
        tracking=True
    )

    narration = fields.Char(
        string="Memo / Reference",
        help="Short memo/reference for this payment."
    )

    # Operational flags
    allow_overpayment = fields.Boolean(
        string="Allow Overpayment",
        help="If enabled, allows paying more than residual; extra becomes credit."
    )
    allow_underpayment = fields.Boolean(
        string="Allow Underpayment",
        help="If enabled, allows paying less than residual and leaves invoice partially paid."
    )

    # Line items (split payments)
    line_ids = fields.One2many(
        "clinic.billing.payment.line",
        "payment_id",
        string="Split Lines",
        copy=True
    )

    # Totals
    amount_total = fields.Monetary(
        string="Total Amount",
        compute="_compute_amounts",
        store=False
    )
    amount_fee = fields.Monetary(
        string="Total Processing Fee",
        compute="_compute_amounts",
        store=False
    )
    amount_net = fields.Monetary(
        string="Net To Reconcile",
        compute="_compute_amounts",
        store=False,
        help="Total - fees (informational; accounting uses line setup)."
    )

    payments_generated_ids = fields.Many2many(
        "account.payment",
        "clinic_payment_to_account_payment_rel",
        "clinic_payment_id",
        "account_payment_id",
        string="Generated Account Payments",
        readonly=True,
        help="Account payments generated by this clinic payment."
    )

    # ---------------------------------------------------------------------
    # Registry helper for soft deps
    # ---------------------------------------------------------------------
    @api.model
    def _model(self, model_name):
        return self.env[model_name] if model_name in self.env else False

    # ---------------------------------------------------------------------
    # Computes
    # ---------------------------------------------------------------------
    @api.depends("line_ids.amount", "line_ids.fee_amount")
    def _compute_amounts(self):
        for rec in self:
            total = sum(l.amount for l in rec.line_ids)
            fee = sum(l.fee_amount for l in rec.line_ids)
            rec.amount_total = total
            rec.amount_fee = fee
            rec.amount_net = (total - fee) if rec.currency_id else total

    # ---------------------------------------------------------------------
    # Constraints
    # ---------------------------------------------------------------------
    @api.constrains("invoice_id")
    def _check_invoice_required(self):
        for rec in self:
            if not rec.invoice_id:
                raise ValidationError(_("Clinic Invoice is required."))

    @api.constrains("line_ids")
    def _check_lines(self):
        for rec in self:
            if not rec.line_ids:
                raise ValidationError(_("Please add at least one payment line."))
            for l in rec.line_ids:
                if l.amount <= 0:
                    raise ValidationError(_("Payment line amount must be positive."))

    # ---------------------------------------------------------------------
    # Sequence
    # ---------------------------------------------------------------------
    def _next_sequence(self):
        return self.env["ir.sequence"].sudo().next_by_code("clinic.billing.payment") or "/"

    # ---------------------------------------------------------------------
    # Lifecycle
    # ---------------------------------------------------------------------
    def action_confirm(self):
        """Validate basic data and switch to Confirmed."""
        for rec in self:
            if rec.state != "draft":
                continue
            if rec.name in ("/", False, ""):
                rec.name = rec._next_sequence()
            # Extra validations vs invoice residual (informational)
            if rec.move_id:
                residual = rec.move_id.amount_residual
                pay_total = rec.amount_total
                if pay_total > residual and not rec.allow_overpayment:
                    raise UserError(_(
                        "Payment amount (%.2f) exceeds invoice residual (%.2f). "
                        "Enable 'Allow Overpayment' or adjust lines."
                    ) % (pay_total, residual))
                if pay_total < residual and not rec.allow_underpayment:
                    # Not blocking; let them proceed if desired by enabling flag
                    raise UserError(_(
                        "Payment amount (%.2f) is less than invoice residual (%.2f). "
                        "Enable 'Allow Underpayment' to proceed or adjust lines."
                    ) % (pay_total, residual))
            # Hooks
            rec._on_after_confirm()
            rec.state = "confirmed"
        return True

    def _on_after_confirm(self):
        """Hook for gateway pre-authorization, membership reserving, etc."""
        # e.g., call gateway to pre-auth hold if line.method == 'card' with capture later.
        pass

    def action_post(self):
        """
        Create & post account.payment for each line (where applicable),
        then reconcile with invoice. Switch to Posted/Reconciled accordingly.
        """
        for rec in self:
            if rec.state not in ("confirmed", "draft"):
                continue
            if not rec.move_id:
                raise UserError(_("No accounting invoice linked on the clinic invoice."))

            generated_payments = []
            for line in rec.line_ids:
                ap = line._create_account_payment()
                if ap:
                    generated_payments.append(ap.id)

            if generated_payments:
                rec.payments_generated_ids = [(6, 0, generated_payments)]
            # Try to reconcile
            rec._reconcile_to_invoice()

            # Update state based on accounting
            rec.state = "reconciled" if rec.invoice_id.is_paid else "posted"

            # Hooks after posting (commission, audit, membership/insurance finalize)
            rec._on_after_post()
        return True

    def _on_after_post(self):
        """Hook: audit trails, notify, finalize insurance/membership settlements."""
        # Example:
        # if self._model("clinic.audit.log"):
        #     self.env["clinic.audit.log"].sudo().create({ ... })
        pass

    def action_cancel(self):
        """
        Cancel only when no posted account.payments exist or invoice not posted.
        For robust flows, prefer refund rather than cancel after posting.
        """
        for rec in self:
            if rec.state in ("reconciled", "posted"):
                raise UserError(_("Cannot cancel a posted/reconciled payment. Please refund instead."))
            rec._on_before_cancel()
            rec.state = "cancelled"
            rec._on_after_cancel()
        return True

    def _on_before_cancel(self):
        """Hook: rollback gateway pre-auth or membership reservations."""
        pass

    def _on_after_cancel(self):
        """Hook: audit logging on cancellation."""
        pass

    # ---------------------------------------------------------------------
    # Reconciliation
    # ---------------------------------------------------------------------
    def _reconcile_to_invoice(self):
        """
        Reconcile generated payments to the accounting invoice using Odoo APIs.
        Safe against version changes by trying standard flows first.
        """
        for rec in self:
            move = rec.move_id
            if not move or move.state != "posted":
                # Post the invoice first if needed
                if move and move.state != "posted":
                    move.sudo().action_post()

            # Collect posted payment moves from generated account.payments
            payments = rec.payments_generated_ids.filtered(lambda p: p.state in ("in_process", "paid"))
            if not payments:
                continue

            # Attempt to use js_assign_outstanding_line if available (typical)
            for payment in payments:
                # Find the receivable line on the payment move
                pay_receivable_lines = payment.move_id.line_ids.filtered(
                    lambda l: l.account_id.account_type == "asset_receivable"
                    and l.balance < 0  # credit on receivable for inbound payment
                )
                # Fallback: any receivable line on the payment move.
                if not pay_receivable_lines:
                    pay_receivable_lines = payment.move_id.line_ids.filtered(
                        lambda line: line.account_id.account_type == "asset_receivable"
                        and not line.reconciled
                    )
                if not pay_receivable_lines:
                    raise UserError(_(
                        "Accounting payment %s has no open receivable line to reconcile."
                    ) % payment.display_name)

                for payment_line in pay_receivable_lines:
                    if move.payment_state == "paid":
                        break
                    try:
                        # Standard Odoo invoice helper for assigning an outstanding payment.
                        move.js_assign_outstanding_line(payment_line.id)
                    except Exception as primary_error:
                        # Deterministic fallback: reconcile open receivable lines directly.
                        invoice_receivable = move.line_ids.filtered(
                            lambda line: line.account_id.account_type == "asset_receivable"
                            and not line.reconciled
                        )
                        compatible_invoice_lines = invoice_receivable.filtered(
                            lambda line: line.account_id == payment_line.account_id
                        )
                        if not compatible_invoice_lines:
                            raise UserError(_(
                                "Payment %s cannot be reconciled to invoice %s because "
                                "their receivable accounts do not match."
                            ) % (payment.display_name, move.display_name)) from primary_error
                        try:
                            (compatible_invoice_lines | payment_line).reconcile()
                        except Exception as fallback_error:
                            raise UserError(_(
                                "Failed to reconcile accounting payment %s to invoice %s. "
                                "No ClinicOne payment state was finalized.\n\n%s"
                            ) % (
                                payment.display_name,
                                move.display_name,
                                fallback_error,
                            )) from fallback_error

            # Sync clinic invoice state with account.move
            rec.invoice_id._sync_state_from_move()

    # ---------------------------------------------------------------------
    # Smart buttons / UI actions
    # ---------------------------------------------------------------------
    def action_view_account_payments(self):
        self.ensure_one()
        action = self.env.ref("account.action_account_payments").read()[0]
        action.update({
            "domain": [("id", "in", self.payments_generated_ids.ids)],
            "context": {"search_default_customer": 1},
        })
        return action

    def unlink(self):
        locked = self.filtered(lambda rec: rec.state not in ("draft", "cancelled", "failed"))
        if locked:
            raise UserError(_("Only Draft, Cancelled, or Failed clinic payments can be deleted."))
        return super().unlink()

    # ---------------------------------------------------------------------
    # CRUD
    # ---------------------------------------------------------------------
    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get("name") or vals.get("name") in ("/", False):
                vals["name"] = self.env["ir.sequence"].sudo().next_by_code("clinic.billing.payment") or "/"
        recs = super().create(vals_list)
        for rec in recs:
            rec._on_after_create()
        return recs

    def _on_after_create(self):
        """Hook: schedule activities, audit log, etc."""
        pass

    def write(self, vals):
        res = super().write(vals)
        return res


# =============================================================================
# Payment Lines (Split)
# =============================================================================
class ClinicBillingPaymentLine(models.Model):
    """
    One line of split payment:
    - Each line may create one account.payment (for methods that require it).
    - Membership/Insurance lines may either create account.payment in a special
      journal (configured on the line) or use soft-hooks to update wallets/claims.
    """
    _name = "clinic.billing.payment.line"
    _description = "Clinic Billing Payment Line"
    _order = "payment_id, sequence, id"

    # ---------------------------------------------------------------------
    # Relations
    # ---------------------------------------------------------------------
    payment_id = fields.Many2one(
        "clinic.billing.payment",
        string="Payment",
        required=True,
        index=True,
        ondelete="cascade"
    )
    invoice_id = fields.Many2one(
        related="payment_id.invoice_id",
        string="Clinic Invoice",
        store=True,
        readonly=True
    )
    move_id = fields.Many2one(
        related="payment_id.move_id",
        string="Accounting Invoice",
        store=True,
        readonly=True
    )
    partner_id = fields.Many2one(
        related="payment_id.partner_id",
        string="Patient",
        store=True,
        readonly=True
    )
    company_id = fields.Many2one(
        related="payment_id.company_id",
        string="Company",
        store=True,
        readonly=True
    )
    currency_id = fields.Many2one(
        related="payment_id.currency_id",
        string="Currency",
        store=True,
        readonly=True
    )

    # ---------------------------------------------------------------------
    # Core fields
    # ---------------------------------------------------------------------
    sequence = fields.Integer(
        string="Sequence",
        default=10
    )
    method = fields.Selection(
        [
            ("cash", "Cash"),
            ("bank_transfer", "Bank Transfer"),
            ("card", "Card"),
            ("ewallet", "E-Wallet"),
            ("membership", "Membership Wallet"),
            ("insurance", "Insurance"),
            ("voucher", "Voucher"),
            ("other", "Other"),
        ],
        string="Method",
        required=True,
        default="cash",
        help="Payment method used for this portion."
    )
    journal_id = fields.Many2one(
        "account.journal",
        string="Journal",
        domain="[('company_id', '=', company_id)]",
        help="Journal to use when creating the account payment for this line."
    )
    amount = fields.Monetary(
        string="Amount",
        required=True
    )
    fee_amount = fields.Monetary(
        string="Processing Fee",
        help="Gateway/processing fee (informational)."
    )
    net_amount = fields.Monetary(
        string="Net Amount",
        compute="_compute_net",
        store=False,
        help="Amount minus processing fee (informational)."
    )
    reference = fields.Char(
        string="External Reference",
        help="External reference number, e.g., bank trx no, card auth code."
    )

    # Gateway metadata (soft integration)
    gateway_provider = fields.Selection(
        [
            ("midtrans", "Midtrans"),
            ("xendit", "Xendit"),
            ("stripe", "Stripe"),
            ("manual", "Manual"),
            ("none", "None"),
        ],
        string="Gateway Provider",
        default="none"
    )
    gateway_tx_id = fields.Char(
        string="Gateway Transaction ID",
        help="Transaction ID returned by the gateway (if any)."
    )
    ewallet_channel = fields.Selection(
        [
            ("ovo", "OVO"),
            ("gopay", "GoPay"),
            ("shopeepay", "ShopeePay"),
            ("dana", "DANA"),
            ("linkaja", "LinkAja"),
            ("other", "Other"),
        ],
        string="E-Wallet Channel"
    )
    card_scheme = fields.Char(
        string="Card Scheme",
        help="e.g., VISA, MasterCard."
    )
    authorization_code = fields.Char(
        string="Authorization Code",
        help="Card authorization code (if applicable)."
    )

    # Membership & Insurance hints
    membership_reference = fields.Char(
        string="Membership Reference",
        help="Membership wallet/account used for this payment."
    )
    insurance_policy_number = fields.Char(
        string="Insurance Policy",
        help="Insurance policy related to this payment."
    )

    note = fields.Char(
        string="Note",
        help="Optional note for this line."
    )

    account_payment_id = fields.Many2one(
        "account.payment",
        string="Generated Account Payment",
        readonly=True,
        copy=False
    )

    # ---------------------------------------------------------------------
    # Computes
    # ---------------------------------------------------------------------
    @api.depends("amount", "fee_amount")
    def _compute_net(self):
        for rec in self:
            amt = rec.amount or 0.0
            fee = rec.fee_amount or 0.0
            rec.net_amount = max(amt - fee, 0.0)

    # ---------------------------------------------------------------------
    # Validations
    # ---------------------------------------------------------------------
    @api.constrains("amount")
    def _check_amount_positive(self):
        for rec in self:
            if rec.amount <= 0:
                raise ValidationError(_("Payment line amount must be positive."))

    # ---------------------------------------------------------------------
    # Soft dependency access
    # ---------------------------------------------------------------------
    @api.model
    def _model(self, model_name):
        return self.env[model_name] if model_name in self.env else False

    # ---------------------------------------------------------------------
    # Core creation of account.payment
    # ---------------------------------------------------------------------
    def _create_account_payment(self):
        """
        Create & post an account.payment for this line when applicable.
        - For membership/insurance/voucher: either create payment in a designated journal
          (if configured), or rely on hooks to settle wallet/claim without account.payment.
        """
        self.ensure_one()

        # If already created, return it
        if self.account_payment_id:
            if self.account_payment_id.state == "draft":
                self.account_payment_id.sudo().action_post()
            elif self.account_payment_id.state in ("canceled", "rejected"):
                raise UserError(_("The linked accounting payment is cancelled/rejected and cannot be reused."))
            return self.account_payment_id

        # Decide if we should create an account.payment for this method
        create_ap = self._should_create_account_payment()
        ap = False

        if create_ap:
            journal = self._resolve_journal()
            if not journal:
                raise UserError(_("Please set a Journal on the payment line (method: %s).") % (self.method,))

            vals = {
                "payment_type": "inbound",      # customer payment
                "partner_type": "customer",
                "partner_id": self.partner_id.id,
                "amount": self.amount,
                "currency_id": self.currency_id.id,
                "date": self.payment_id.date,
                "memo": self._build_payment_ref(),
                "payment_reference": self.reference or self._build_payment_ref(),
                "journal_id": journal.id,
                "company_id": self.company_id.id,
                "clinic_invoice_id": self.invoice_id.id,
                "clinic_payment_id": self.payment_id.id,
                "clinic_note": self.note or self.reference or self.payment_id.narration,
            }
            ap = self.env["account.payment"].sudo().create(vals)
            # Post it
            ap.sudo().action_post()
            self.account_payment_id = ap.id

        # Hooks for side-effects regardless of account.payment creation
        self._hook_gateway_capture()
        self._hook_membership_debit()
        self._hook_insurance_settlement()
        self._hook_audit_log("create_line_payment", {"line_id": self.id, "ap_id": ap.id if ap else False})

        return ap

    # ---------------------------------------------------------------------
    # Decisions & Resolutions
    # ---------------------------------------------------------------------
    def _should_create_account_payment(self):
        """
        Decide whether to create account.payment for this method.
        Default: True for cash/bank/card/ewallet/transfer/other; False for voucher.
        Membership/Insurance: True if journal is set; else False (handled by hooks).
        """
        if self.method in ("cash", "bank_transfer", "card", "ewallet", "other"):
            return True
        if self.method == "voucher":
            return False
        if self.method in ("membership", "insurance"):
            # If journal is provided, we'll create an accounting entry; otherwise rely on the specific module.
            return bool(self.journal_id)
        return True

    def _resolve_journal(self):
        """Prefer line.journal_id; otherwise try company default inbound payment journal."""
        if self.journal_id:
            return self.journal_id
        # fallback: any bank/cash/general journal for inbound
        Journal = self.env["account.journal"].sudo()
        journal = Journal.search([
            ("type", "in", ("bank", "cash", "general")),
            ("company_id", "=", self.company_id.id)
        ], limit=1)
        return journal

    def _build_payment_ref(self):
        ref = "[%s] %s" % (self.method.upper(), self.payment_id.name or "")
        if self.reference:
            ref = "%s - %s" % (ref, self.reference)
        if self.gateway_provider and self.gateway_provider != "none":
            ref = "%s (%s:%s)" % (ref, self.gateway_provider, self.gateway_tx_id or "-")
        return ref

    # ---------------------------------------------------------------------
    # Hooks (membership / insurance / gateway / audit)
    # ---------------------------------------------------------------------
    def _hook_membership_debit(self):
        """
        Deduct from membership wallet (clinic_membership), if available.
        Implemented by inheriting modules; here we just no-op safely.
        """
        # Example (pseudo in membership module):
        # Wallet = self._model("clinic.wallet")
        # if Wallet and self.method == "membership":
        #     Wallet.debit(self.partner_id, self.amount, reference=self.payment_id.name)
        return

    def _hook_insurance_settlement(self):
        """
        Notify/settle insurance module (clinic_insurance) if method is insurance.
        """
        # Example (pseudo in insurance module):
        # Claim = self._model("clinic.insurance.claim")
        # if Claim and self.method == "insurance":
        #     Claim.register_settlement(self.invoice_id.id, self.amount, policy=self.insurance_policy_number)
        return

    def _hook_gateway_capture(self):
        """
        Capture/notify gateway (midtrans/xendit/stripe) if applicable.
        """
        # Example (pseudo in gateway module):
        # Tx = self._model("clinic.billing.gateway.tx")
        # if Tx and self.gateway_provider in ("midtrans", "xendit", "stripe") and self.gateway_tx_id:
        #     Tx.capture(self.gateway_provider, self.gateway_tx_id, amount=self.amount)
        return

    def _hook_audit_log(self, event, payload=None):
        """
        Send audit log to clinic_audit if installed.
        """
        # Example:
        # Audit = self._model("clinic.audit.log")
        # if Audit:
        #     Audit.sudo().create({
        #         "event": event,
        #         "payload": payload or {},
        #         "res_model": self._name,
        #         "res_id": self.id,
        #     })
        return


# =============================================================================
# Extensions on Clinic Billing Invoice (payments view & helpers)
# =============================================================================
class ClinicBillingInvoice_PaymentExt(models.Model):
    _inherit = "clinic.billing.invoice"

    billing_payment_ids = fields.One2many(
        "clinic.billing.payment",
        "invoice_id",
        string="Clinic Payments"
    )
    billing_payments_count = fields.Integer(
        string="Clinic Payments Count",
        compute="_compute_billing_payments_count"
    )

    def _compute_billing_payments_count(self):
        for rec in self:
            rec.billing_payments_count = len(rec.billing_payment_ids)

    def action_open_billing_payments(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Clinic Payments"),
            "res_model": "clinic.billing.payment",
            "view_mode": "list,form",
            "domain": [("invoice_id", "=", self.id)],
            "context": {"default_invoice_id": self.id},
        }

    def action_register_split_payment(self):
        """
        Shortcut action: open new clinic.billing.payment in context of this invoice.
        """
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Register Split Payment"),
            "res_model": "clinic.billing.payment",
            "view_mode": "form",
            "target": "current",
            "context": {
                "default_invoice_id": self.id,
                "default_date": fields.Date.context_today(self),
            },
        }

