# -*- coding: utf-8 -*-
{
    "name": "ClinicOne - Branch Management",
    "summary": "Enterprise multi-branch and franchise governance with branch-aware segregation.",
    "version": "19.0.2.0.0",
    "category": "ClinicOne/Operations",
    "author": "IG @odoocamp",
    "website": "https://www.247opensource.com",
    "license": "AGPL-3",
    "depends": [
        "base",
        "base_setup",
        "mail",
        "web",
        "contacts",
        "resource",
        "hr",
        "stock",
        "account",
        "clinic_base",
    ],
    "data": [
        "security/clinic_branch_security.xml",
        "security/ir.model.access.csv",
        "views/branch_views.xml",
        "views/branch_location_views.xml",
        "views/res_users_views.xml",
        "views/res_company_views.xml",
        "views/stock_warehouse_views.xml",
        "views/account_move_views.xml",
        "views/hr_employee_views.xml",
        "views/res_partner_views.xml",
        "views/menu_views.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
}
